### ISSUE TITLE
Background of messages (behind message bubbles) don't have the correct background color

### ISSUE THREAD

**Issue by dubcusb** [vednoc/dark-whatsapp#102]
- **Browser**: Vivaldi 2.10
- **Dark-WhatsApp version**: v2.0.6
- **Additional context**: This issue has been around for quite a while, even in v1. I never made an issue because I didn't use WhatsApp Web regularly and I thought it was going to be fixed soon anyway. 
- **Screenshot**: 
![image](https://user-images.githubusercontent.com/21978144/72763261-cb137b80-3bc1-11ea-9157-6f9f7d722d9d.png)
I hope the title and the screenshot are clear enough.

**Comment by vednoc** [comment]
I'm unable to replicate this issue in multiple browsers, including Vivaldi. Something that obvious would've been fixed long time ago unless it's some obscure edge-case.

Check to see if the issue is still there when using a different profile or even a different browser.

**Comment by dubcusb** [comment]
Oh I'm dumb, it turns out another extension was conflicting with Stylus (dark mode), and I had forgotten to disable it for WhatsApp Web. Sorry to bother you with this unrelated issue haha.
Love the style btw, thanks for the work you put into this!

**Comment by vednoc** [comment]
No problems, things like that happen. I'm glad that you figured it out. Enjoy! :smiley: :tada:
