### ISSUE TITLE
Multiple Selection Menu is shown White

### ISSUE THREAD

**Issue by gatorv** [vednoc/dark-whatsapp#109]
The multiple message selection menu is white
![image](https://user-images.githubusercontent.com/1844624/73092038-672ed280-3ea1-11ea-9a23-0dd6cd0c86ac.png)

Relevant HTML
`      <div class="_2aUit" style="transform: translateY(0%);"><button class="_3f5U8"><span data-icon="x" class=""><svg
        xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
        <path opacity=".45" fill="#263238"
          d="M19.1 17.2l-5.3-5.3 5.3-5.3-1.8-1.8-5.3 5.4-5.3-5.3-1.8 1.7 5.3 5.3-5.3 5.3L6.7 19l5.3-5.3 5.3 5.3 1.8-1.8z">
        </path>
      </svg></span></button><span class="nGgVY">2 selected</span><button class="_3f5U8" title="Star messages"><span
      data-icon="star-btn" class=""><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
        <path fill="#263238"
          d="M11.1 16.8l-4.4 3.1c-.7.5-1.5-.1-1.3-.9L7 13.9c.1-.3 0-.7-.3-.9L2.4 9.7c-.6-.4-.3-1.4.5-1.4l5.4-.1c.3 0 .6-.2.7-.6l1.8-5.1c.2-.7 1.3-.7 1.5 0l1.8 5.1c.1.3.4.5.7.5l5.4.1c.8 0 1.1 1 .5 1.4L16.4 13c-.3.2-.4.5-.3.9l1.6 5.2c.2.7-.6 1.3-1.2.9L12 16.8c-.3-.2-.6-.2-.9 0z">
        </path>
      </svg></span></button><button class="_3f5U8" title="Delete messages"><span data-icon="delete" class=""><svg
        xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
        <path fill="#263238" d="M6 18c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V6H6v12zM19 3h-3.5l-1-1h-5l-1 1H5v2h14V3z"></path>
      </svg></span></button><button class="_3f5U8" title="Forward messages"><span data-icon="forward" class=""><svg
        xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
        <path fill-rule="evenodd" clip-rule="evenodd" fill="#263238"
          d="M14.278 4.813c0-.723.873-1.085 1.383-.574l6.045 6.051a.81.81 0 0 1 0 1.146l-6.045 6.051a.81.81 0 0 1-1.383-.574v-2.732c-5.096 0-8.829 1.455-11.604 4.611-.246.279-.702.042-.602-.316 1.43-5.173 4.925-10.004 12.206-11.045V4.813z">
        </path>
      </svg></span></button><button class="_3f5U8" title="Download"><span data-icon="download" class=""><svg
        xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
        <path fill="#263238" d="M18.9 10.3h-4V4.4H9v5.9H5l6.9 6.9 7-6.9zM5.1 19.2v2H19v-2H5.1z"></path>
      </svg></span></button></div>`

**Comment by vednoc** [comment]
The v1 is unsupported; install the [v2](https://github.com/vednoc/dark-whatsapp/wiki/Installation).
