### ISSUE TITLE
How can I use this theme as a userscript?

### ISSUE THREAD

**Issue by raulcraveiro** [vednoc/dark-whatsapp#110]
### I would like to be able do the following

How can I use this theme as a userscript? Because I like to use nativefier to create my Whatsapp client, and I need to have a userscript.js to inject on it.

**Comment by vednoc** [comment]
After taking a quick look at the [inject][0] in their API, it looks like your best bet is to use [Franz/Ferdi way of installing][1] the userstyle. That way you clone the repository and inject the CSS.

Another way that I can think of would be to inject a JS script that will fetch the userstyle and inject it into the DOM. This way the update process will _probably_ be automatic.

Let me know how things go and/or if you need help.


[0]: https://github.com/jiahaog/nativefier/blob/master/docs/api.md#inject
[1]: https://github.com/vednoc/dark-whatsapp/wiki/Installation#installing-in-franz--or-ferdi-

**Comment by raulcraveiro** [comment]
It worked injecting the css! Thank you so much <3
