### ISSUE TITLE
Border around profile picture while typing

### ISSUE THREAD

**Issue by ofurkancoban** [vednoc/dark-whatsapp#111]
Hello, I really like this project. Can you add a mode of a border around profile picture while contact is typing. That will be very useful in compact mode. Thank you. Best Regards.

**Comment by vednoc** [comment]
Cool idea, but it's unlikely to be implemented due to how the markup is structured. I'll give it a go and see what happens.

**Comment by vednoc** [comment]
I couldn't find a proper solution due to how WhatsApp applies the typing indicator. It would end up being too buggy and break message content, so I'm deciding to leave it out for the time being.
