### ISSUE TITLE
UI problem on hover message bubble

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [vednoc/dark-whatsapp#114]
- **Browser**: Firefox 64 ESR
- **Dark-WhatsApp version**: Lastest version from Stylish
- **Additional context**: 
- **Screenshot**: 
![Screenshot from 2020-02-02 10-47-41](https://user-images.githubusercontent.com/17345129/73604721-8ff24e80-45aa-11ea-8782-c229ec755e9b.png)

Look at the message bubble, Its hover state of message.

**Comment by vednoc** [comment]
Replace Stylish with Stylus and install the version 2 of Dark WhatsApp. Check the [wiki] for instructions.

[wiki]: https://github.com/vednoc/dark-whatsapp/wiki/Installation
