### ISSUE TITLE
Emojis not showing

### ISSUE THREAD

**Issue by otaviopires** [vednoc/dark-whatsapp#115]
- **Browser**: Google Chrome Version 80.0.3987.87 (Official Build) (64-bit)
- **Dark-WhatsApp version**: 2.1.1
- **Additional context**: windows 10 19041.21
- **Screenshot**: 
![Screenshot_28](https://user-images.githubusercontent.com/1145551/74031576-a6c0e880-4990-11ea-9481-d4635904bb2c.png)

**Comment by vednoc** [comment]
Quite odd. Until we figure out why they're broken, you can disable transparent emoji images like shown [on the wiki][0].

@E-RELevant does this happen on your end?

[0]: https://github.com/vednoc/dark-whatsapp/wiki/Configuration#transparent-emojis

**Comment by E-RELevant** [comment]
> @E-RELevant does this happen on your end?

It takes a second to pull all the data off but it works without a problem for me (using the same browser, os and `dark-whatsapp` version)
![image](https://user-images.githubusercontent.com/20738487/74081629-dc7dd400-4a59-11ea-8eb5-b0b49b9a1465.png)
Maybe that is an internet connection problem?

**Comment by otaviopires** [comment]
> Maybe that is an internet connection problem?

I'll keep trying in other netwoks to see if the problem persists

**Comment by E-RELevant** [comment]
> I'll keep trying in other networks to see if the problem persists

Does it still happen to you on other networks and/or devices?

**Comment by otaviopires** [comment]
`Does it still happen to you on other networks and/or devices?`

I've tested in other networks and it works fine.
Maybe is a block on my firewall.
I'll be closing this issue.
Thanks for the help guys! 👍

**Comment by akshansh1998** [comment]
emojis in my pc are getting misplaced... like the thumbnails for all emojis are messed up something,
![image](https://user-images.githubusercontent.com/26520096/75013904-31363b80-54ab-11ea-954f-1e9d933186e8.png)

I tapped the first one which is actually a smile emoji but as you can see it is showing wrong thumbnail

**Comment by vednoc** [comment]
Hey @akshansh1998,

WhatsApp added new emoji images and broke what we had. In `v2.2.1` I did a forced-reset so that this issue doesn't happen. Possibly today, in `v2.2.2`, I'll merge in the new transparent emoji images.

Your input-bar has gray color, so you're still on `v2.2.0`. Update to the latest version and you'll be fine.

**Comment by otaviopires** [comment]
> Hey @akshansh1998,
> 
> WhatsApp added new emoji images and broke what we had. In `v2.2.1` I did a forced-reset so that this issue doesn't happen. Possibly today, in `v2.2.2`, I'll merge in the new transparent emoji images.
> 
> Your input-bar has gray color, so you're still on `v2.2.0`. Update to the latest version and you'll be fine.

thanks for the tip, I've updated it.
