### ISSUE TITLE
WhatsApp Business chats filter issues

### ISSUE THREAD

**Issue by tinyCoder32** [vednoc/dark-whatsapp#122]
![image](https://user-images.githubusercontent.com/17817239/75031384-2a152a80-54b7-11ea-962e-13474673ddbd.png)

**Comment by vednoc** [comment]
Can't test this as I don't use WA Business. Could you copy-paste HTML for the entire menu? That would help a lot!

**Comment by tinyCoder32** [comment]
`<div tabindex="-1" class="_2hHc6" style="transform-origin: left top; left: 480.816px; top: 112.969px; transform: scale(1); opacity: 1;"><ul class="_3z3lc"><div class="KrrR1">Chats</div><li tabindex="-1" class="_3cfBY _2yhpw _3BqnP" data-animate-dropdown-item="true" style="opacity: 1;"><div class="_2eGMB"><span data-icon="search-unread" class=""><svg width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M19.718 11.16v4.181c0 .913-.772 1.659-1.718 1.659H7.718C6.773 17 6 16.254 6 15.341V10.5L3.408 6.743C3.125 6.333 3.3 6 3.795 6h9.817a4.5 4.5 0 0 0 6.107 5.16z" id="Path" fill-opacity=".55" fill="#263238"></path><path d="M18 10a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" id="Oval" fill-opacity=".4" fill="#727475"></path></svg></span><div class="_2NyQz">Unread chats</div></div></li><li tabindex="-1" class="_3cfBY _2yhpw _3BqnP" data-animate-dropdown-item="true" style="opacity: 1;"><div class="_2eGMB"><span data-icon="group" class=""><svg width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M16.67 9.76a2.394 2.394 0 0 1 .029-1.226 2.222 2.222 0 0 1 .332-.664 2.114 2.114 0 0 1 1.106-.774A2.32 2.32 0 0 1 18.803 7c1.247 0 2.2.953 2.2 2.2 0 1.247-.953 2.2-2.2 2.2a2.352 2.352 0 0 1-.666-.096 2.219 2.219 0 0 1-.664-.332 2.115 2.115 0 0 1-.774-1.106 2.42 2.42 0 0 1-.028-.106zm-9.295-.218a2.27 2.27 0 0 1-.143.528 2.163 2.163 0 0 1-.26.46 2.117 2.117 0 0 1-1.106.774 2.31 2.31 0 0 1-.666.096c-1.247 0-2.2-.953-2.2-2.2C3 7.953 3.953 7 5.2 7a2.352 2.352 0 0 1 .666.096 2.182 2.182 0 0 1 .664.332 2.115 2.115 0 0 1 .774 1.106 2.227 2.227 0 0 1 .071.324c.033.227.033.457 0 .684zm15.418 4.764a3.165 3.165 0 0 1 .207.37V16h-3.95l-.016-.107c-.038-.152-.098-.408-.18-.543a5.534 5.534 0 0 0-.363-.543 7.06 7.06 0 0 0-.587-.686 7.212 7.212 0 0 0-1.627-1.252l-.053-.029c.031-.015.061-.032.094-.047l.06-.03c.599-.268 1.352-.456 2.287-.456.936 0 1.688.188 2.298.462a4.606 4.606 0 0 1 .989.612 4.312 4.312 0 0 1 .715.746c.048.063.09.123.126.18zm-7.621-6.562a3.543 3.543 0 0 1-.063 1.334 3.397 3.397 0 0 1-.15.457 3.19 3.19 0 0 1-.383.68 3.124 3.124 0 0 1-1.189.973 3.268 3.268 0 0 1-.76.248c-.221.043-.445.064-.67.064-1.84 0-3.25-1.408-3.25-3.25S10.118 5 11.958 5a3.476 3.476 0 0 1 .985.142 3.25 3.25 0 0 1 .98.49 3.124 3.124 0 0 1 1.037 1.333 3.204 3.204 0 0 1 .213.78zm2.653 8.075c.065.107.123.217.175.33V18H6v-1.85s.023-.054.072-.147a3.81 3.81 0 0 1 .103-.184 4.904 4.904 0 0 1 .309-.46 5.826 5.826 0 0 1 .509-.595 6.287 6.287 0 0 1 1.871-1.323c.03-.013.057-.028.087-.041.86-.388 1.691-.657 3.036-.657s2.202.27 3.078.664a6.37 6.37 0 0 1 1.943 1.356 6.05 6.05 0 0 1 .69.854c.049.074.09.141.127.202zm-12.873.075L4.945 16H1v-1.324s.04-.088.125-.23c.025-.042.057-.089.091-.14a3.665 3.665 0 0 1 .286-.38 4.214 4.214 0 0 1 .556-.545 4.41 4.41 0 0 1 1-.617c.6-.27 1.352-.457 2.287-.457.936 0 1.689.188 2.287.457l.06.029c.027.012.051.026.077.039-.06.033-.12.066-.178.1a7.14 7.14 0 0 0-1.841 1.543 6.238 6.238 0 0 0-.471.634c-.058.088-.1.167-.152.256-.048.08-.07.148-.101.206-.072.136-.074.323-.074.323z" fill="currentColor"></path></svg></span><div class="_2NyQz">Groups</div></div></li><li tabindex="-1" class="_3cfBY _2yhpw _3BqnP" data-animate-dropdown-item="true" style="opacity: 1;"><div class="_2eGMB"><span data-icon="search-broadcasts" class=""><svg width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M13.389 17.998c-.63 1.18-1.856 1.98-3.265 1.98-2.053 0-3.717-1.7-3.717-3.798 0-.185.013-.368.038-.546L4 14.8v-5.67l12-4.086v13.842l-2.112-.719-.499-.17zm-1.295-.44l-4.21-1.434-.145-.05-.002.106c0 1.346 1.069 2.438 2.387 2.438.818 0 1.54-.42 1.97-1.06zM17 4.704l1.988-.677v15.876L17 19.228V4.705z" fill-opacity=".55" fill="#263238"></path></svg></span><div class="_2NyQz">Broadcast lists</div></div></li><div class="KrrR1">Labels</div><li tabindex="-1" class="_3cfBY _2yhpw _3BqnP" data-animate-dropdown-item="true" style="opacity: 1;"><button class="_29Ziv"><div class="_3Zium _36d6G"><div class="yKiIK"><svg width="18px" height="12px" viewBox="0 0 18 12" class="_3-Rfz"><path fill="#5696ff" d="M11.208,0.925H2.236C1.556,0.925,1,1.565,1,2.357V9.57C1,10.362,1.556,11,2.236,11h8.972 c0.414,0,0.785-0.237,1.007-0.604l2.701-4.433L12.215,1.53C11.993,1.162,11.622,0.925,11.208,0.925z"></path></svg></div><span class="_2UekJ">Must Reply</span></div></button></li><li tabindex="-1" class="_3cfBY _2yhpw _3BqnP" data-animate-dropdown-item="true" style="opacity: 1;"><button class="_29Ziv"><div class="_3Zium _36d6G"><div class="yKiIK"><svg width="18px" height="12px" viewBox="0 0 18 12" class="_3-Rfz"><path fill="#ff7a6b" d="M11.208,0.925H2.236C1.556,0.925,1,1.565,1,2.357V9.57C1,10.362,1.556,11,2.236,11h8.972 c0.414,0,0.785-0.237,1.007-0.604l2.701-4.433L12.215,1.53C11.993,1.162,11.622,0.925,11.208,0.925z"></path></svg></div><span class="_2UekJ">Urgent</span></div></button></li><li tabindex="-1" class="_3cfBY _2yhpw _3BqnP" data-animate-dropdown-item="true" style="opacity: 1;"><button class="_29Ziv"><div class="_3Zium _36d6G"><div class="yKiIK"><svg width="18px" height="12px" viewBox="0 0 18 12" class="_3-Rfz"><path fill="#54c166" d="M11.208,0.925H2.236C1.556,0.925,1,1.565,1,2.357V9.57C1,10.362,1.556,11,2.236,11h8.972 c0.414,0,0.785-0.237,1.007-0.604l2.701-4.433L12.215,1.53C11.993,1.162,11.622,0.925,11.208,0.925z"></path></svg></div><span class="_2UekJ">WAW+ Suggestion</span></div></button></li></ul></div>`

**Comment by vednoc** [comment]
Awesome, thank you! I'll look into it whenever the electricity comes back. We're having a power outage for some reason, thankfully I can use my phone in the meantime. 😄

**Comment by vednoc** [comment]
@tinyCoder32 I also changed the label colors. Is there a list of colors to choose from, how does it work? If you think it would be better to remove styles for them then I'll do it. :smile:

**Comment by tinyCoder32** [comment]
Thank you so much, it works perfectly now!

<img width="236" alt="image" src="https://user-images.githubusercontent.com/17817239/75081583-bd367a80-5520-11ea-8aad-2c5742565a94.png">

**Comment by tinyCoder32** [comment]
By the way, can you please fix the version 1 emojis? I have users using your version 1 at a chrome extension and they are reporting false emojis after WhatsApp latest update.

Please.

**Comment by tinyCoder32** [comment]
You Cannot change the label colors, my friend. Because the users changes them/ or whatsapp randomly picks them for you.

<img width="363" alt="image" src="https://user-images.githubusercontent.com/17817239/75081890-0e933980-5522-11ea-88a9-b20350bde76e.png">

**Comment by vednoc** [comment]
> By the way, can you please fix the version 1 emojis? I have users using your version 1 at a chrome extension and they are reporting false emojis after WhatsApp latest update.

All you have to do is copy-paste the following lines into your code.
https://github.com/vednoc/dark-whatsapp/blob/master/wa.user.css#L419-L1108


> You Cannot change the label colors, my friend. Because the users changes them/ or whatsapp randomly picks them for you.

If that's the case then I'll remove the styles in the next update.

**Comment by vednoc** [comment]
Somehow I managed to miss the group icon, will fix that as well in the next version. :sweat_smile:

**Comment by tinyCoder32** [comment]
Yes, i noticed you forgot it but i thought it is not a major thing.

Thanks for all your efforts.

**Comment by vednoc** [comment]
Oh, I think emojis will _magically_ work for majority of the available emojis given that I updated [vednoc/wae] repository, unless you're self-hosting the images somewhere else. The added emojis will still have the white background tho.

[vednoc/wae]: https://github.com/vednoc/wae/

**Comment by tinyCoder32** [comment]
Thanks! no, im using the images hosted on your repo.
