### ISSUE TITLE
The emojis in the emoji tab are all transparent

### ISSUE THREAD

**Issue by obvionaoe** [vednoc/dark-whatsapp#125]
- **Browser**: Rambox (Chromium)
- **Dark-WhatsApp version**: 2.2.2
- **Additional context**:  the emojis in the emoji tab are all transparent, as in, the emoji divs are there, but the textures are missing
- **Screenshot**: 
![transparent emojis](https://user-images.githubusercontent.com/35278323/76634057-a8f10680-653d-11ea-82cf-5ccbbcdaaa38.png)

**Comment by hertelukas** [comment]
Why is this closed? I still encounter this issue.

**Comment by vednoc** [comment]
@hertelukas You might not be running the `v2.3.4` if you have this issue. Transparent emoji images have been set to the defaults in [this commit][0] that was released in `v2.3.1`.

[0]: bde4421ce21bd09aacea0e21680f91c7e51cfdc5

**Comment by hertelukas** [comment]
@vednoc I noticed that, on my Windows machine I don't run in this issue. I double checked the version on Linux and reinstalled Dark-Whatsapp, still getting the same issue. But some emojis are appearing.

**Comment by vednoc** [comment]
@hertelukas I run Linux myself and there are no issues on my end. Try installing dev build from https://github.com/vednoc/dark-whatsapp/issues/137#issuecomment-605663010 to see if it fixes anything, otherwise I'll need more info about your setup in order to debug/reproduce this issue.
