### ISSUE TITLE
Custom background image isn't work after 2.3.0 update

### ISSUE THREAD

**Issue by alnviana** [vednoc/dark-whatsapp#127]
After last upgrade, my custom background image isn't applying anymore. I'm using Stylus 1.5.10 and already tried to reset configurations, but don't worked.

**Comment by vednoc** [comment]
Are you setting the image via configuration menu or by modifying the code?

If it's the former, make sure to have the following set:
- Custom app background: `Custom background image`
- Custom background image link: 
    - The link must be inside of `url('valid-link-here'` otherwise it won't work.
    - Example: `url('https://images.unsplash.com/photo-1545128485-c400e7702796?&w=1280&q=80')`

**Comment by alnviana** [comment]
Configuration menu. It was working before the automatic update.

This is my value:
url('https://cdn.suwalls.com/wallpapers/minimalistic/red-sun-rays-glowing-in-space-52762-2560x1600.jpg')

And here the CSS variable:
![image](https://user-images.githubusercontent.com/31132223/77338182-bf028200-6d08-11ea-9f88-ed77cfb1afb1.png)

When i change manually, works.

**Comment by vednoc** [comment]
It works without issues on my end. Looking at the [commit][0] that changed this setting, there doesn't to be anything that would cause this behavior.

Can you show me the computed tab for this element? It's the `::after` element in your screenshot.
![image](https://user-images.githubusercontent.com/18245694/77342518-98f0d800-6d30-11ea-9104-f878bb83ca76.png)

[0]: https://github.com/vednoc/dark-whatsapp/commit/192e124db14ee8f2bd61518f3924333dcb21ba1b

**Comment by alnviana** [comment]
I can't find this:
![image](https://user-images.githubusercontent.com/31132223/77344655-3ee11a00-6d12-11ea-9527-caccc8bfbed6.png)
![image](https://user-images.githubusercontent.com/31132223/77344724-59b38e80-6d12-11ea-8086-6bfb710af2e5.png)

I forgot to say, i'm using Firefox 74.

I tried to use v2.2.2 again from this file:
https://github.com/vednoc/dark-whatsapp/blob/67f219b1594ed5145ae00fe23bd8a8e67c2f01a7/wa.user.styl
In this case, worked again...

**Comment by vednoc** [comment]
> When i change manually, works.

Just to clarify, did you manually choose the `Custom background image` from the dropdown or did you manually change `bg-image` variable? It's sort of confusing now that I think about it. :sweat_smile:

In `2.3.0` update you have to explicitly choose that you want to use the custom background image, which isn't the case in `2.2.2` as it's set to `custom` by default.

**Comment by alnviana** [comment]
Sorry, when i manually change --bg-image on Inspector, works.
And you are right, i never changed to Custom. I changed and now worked.
![image](https://user-images.githubusercontent.com/31132223/77366423-be80e000-6d36-11ea-81dc-824c00dca9a2.png)

Thanks for the support and for the excellent work on this theme.

**Comment by vednoc** [comment]
You'll probably have to change the hue back to 0; the default `320deg` is used for all custom background images.

I'm glad you like it, have fun using and customizing it! :blush:
