### ISSUE TITLE
Advertisment of your blog

### ISSUE THREAD

**Issue by L4B0MB4** [vednoc/dark-whatsapp#128]
This isn't really a bug but its also not a question or a feature request.

I just had to copy the url of your blog out of the css variable because its not selectable or click-able. I guess it would increase the visitor count of your blog if it would be :) 

Maybe you are already aware of this problem, in this case I apologize for creating an unnecessary issue.

PS: I like your theme a lot 👍 

![image](https://user-images.githubusercontent.com/37332872/77537927-2baf8500-6e9f-11ea-8ab4-8f021d13f9c5.png)

**Comment by vednoc** [comment]
It probably would, but CSS can only add visual changes and this requires editing or embedding an HTML element. It's also unfortunate that text can't be copied from pseudo-elements.

Besides, it's not what I'm after. This is the only way of announcing changes, and I like providing updates in a way that everyone can see them. I agree that it's not convenient to type the URL manually, I'm still searching for how to make the UX better.

> Maybe you are already aware of this problem, in this case I apologize for creating an unnecessary issue.

I'm glad you asked, this should be added to [FAQ][0] and it'll be visible when someone enters similar keywords, so it'll be nice to have it here as well.

> PS: I like your theme a lot +1

Thank you on the kind words. :blush: 

P.S. Try [customizing][0] the theme, if you haven't tried it already. :smiley:

[0]: https://github.com/vednoc/dark-whatsapp/wiki/FAQ
[1]: https://github.com/vednoc/dark-whatsapp/wiki/Configuration
