### ISSUE TITLE
Messages sent are marked as read 

### ISSUE THREAD

**Issue by Andrewzz** [vednoc/dark-whatsapp#131]
Messages sent to groups or to a single person are being marked as read (double blue icon), when the message is delivered, doesn't matter if it has been read or not.

- **Browser**: Chrome
- **Dark-WhatsApp version**:2.3.1
- **Additional context**:
- **Screenshot**:
![image](https://user-images.githubusercontent.com/161734/77717058-46c4e680-6fbe-11ea-80c0-986fd9114814.png)

**Comment by vednoc** [comment]
I knew I made some basic mistake because it was going too well. :sweat_smile: 

Thanks for reporting the issue and bringing it to my attention!
