### ISSUE TITLE
Message status icons are blue even when the message isn't seen

### ISSUE THREAD

**Issue by stormsilence** [vednoc/dark-whatsapp#134]

**Comment by thiagobraga** [comment]
Seems that the current version 2.3.2 launched 25 minutes ago already fixed this bug.

**Comment by nik3348** [comment]
Not for me, still constant blue ticks as of 2.3.2

**Comment by vednoc** [comment]
> Not for me, still constant blue ticks as of 2.3.2

Could you show me a screenshot of the area where they're still broken? Just blur the sensitive information.

**Comment by BenitesGui** [comment]
I still have the problem on 2.3.2, in all messages 
![image](https://user-images.githubusercontent.com/12888298/77773455-6690f480-7028-11ea-95f8-1e9358b49ee8.png)
![image](https://user-images.githubusercontent.com/12888298/77773583-917b4880-7028-11ea-9e6e-435f3ea4be0b.png)

**Comment by stormsilence** [comment]
> Seems that the current version 2.3.2 launched 25 minutes ago already fixed this bug.

I'm afraid it didn't work for me either... Now all the ticks are grey, regardless of whether they've been read or not.

![image](https://user-images.githubusercontent.com/37045808/77773645-e7271380-706f-11ea-87c0-bcfb2cc357ca.png)

**Comment by stormsilence** [comment]
Sorry to keep bothering you, but I'm afraid I've found another little snag... 
![image](https://user-images.githubusercontent.com/37045808/77774173-a8de2400-7070-11ea-8bee-785e33850cc3.png)

**Comment by Andrewzz** [comment]
I would say there is a problem with your installaiton, as the down arrow is also white. It is working for me with the latest release. What version are you running?

**Comment by vednoc** [comment]
I'm not sure why it works for some and doesn't work for others. Will do some more research, maybe even rewrite this part from the scratch.

> > Seems that the current version 2.3.2 launched 25 minutes ago already fixed this bug.
> 
> I'm afraid it didn't work for me either... Now all the ticks are grey, regardless of whether they've been read or not.

Looks like it's still using `2.3.0` version. :thinking: Try manually updating or reinstalling from GitHub.

**Comment by nik3348** [comment]
Actually yea it worked, had to reinstall it though update didn't work

**Comment by vednoc** [comment]
I was unable to reproduce it in both Chromium and Firefox. Highly suggested to reinstall it from [this link][0] if it doesn't work, just to be sure you have the latest update.

> Actually yea it worked, had to reinstall it though update didn't work

Awesome! I'm glad that it works now. :smiley: 

[0]: https://raw.githubusercontent.com/vednoc/dark-whatsapp/master/wa.user.styl

**Comment by stormsilence** [comment]
Hey so I reinstalled it with the code directly from github and its working great, thank you so much!
Also, I really appreciate how active you are about dealing with these issues and how helpful you were. Thanks a ton, man. Massive respect.

**Comment by vednoc** [comment]
> Hey so I reinstalled it with the code directly from github and its working great, thank you so much!
> Also, I really appreciate how active you are about dealing with these issues and how helpful you were. Thanks a ton, man. Massive respect.

Thanks for the kinds word, I'm always happy to help.
May your eyes enjoy the dark mode once again! :smile:
