### ISSUE TITLE
Video progress bar does not show progress

### ISSUE THREAD

**Issue by TimoMeijer** [vednoc/dark-whatsapp#136]
- **Browser**: Chrome
- **Dark-WhatsApp version**: v2.3.2
- **Additional context**: When playing a received video, the progress is not displayed, additionally, when hovering over it, the dot is behind the progress bar.
- **Screenshot**:
![image](https://user-images.githubusercontent.com/1517813/77786278-d40b4800-705d-11ea-9f75-3a70bc4aa668.png)
![image](https://user-images.githubusercontent.com/1517813/77786327-e8e7db80-705d-11ea-82e9-558bf8c0329d.png)

**Comment by TimoMeijer** [comment]
v2.3.3 did not seem to have fixed this issue:
![image](https://user-images.githubusercontent.com/1517813/77809562-78a67d80-7090-11ea-8bc2-1cd620c62669.png)

**Comment by vednoc** [comment]
Added more info here in #142.
