### ISSUE TITLE
"Unhover" delay option for compact mode?

### ISSUE THREAD

**Issue by SeerLite** [vednoc/dark-whatsapp#138]
**Describe the change you'd like**:
An option to set the "unhover" animation delay in compact mode. Right now, the "Compact mode on-hover delay" option only covers when the cursor starts hovering over the contact list, but not when it leaves. Is this delay possible to configure in CSS?

**Additional context**:
I feel like the animation takes too long to happen. It's really annoying to have to wait for the hardcoded animation time when I need to quickly see what I'm typing after switching chats but forget to move the cursor away from the contact list/move it too late.

As always, thanks for the great theme, and the quick fixes that come when WhatsApp Web updates!

**Comment by vednoc** [comment]
If I'm not wrong, adding this should be pretty straight-forward. The compact mode is a bit broken as well, I'm working on it at the moment.

**Comment by SeerLite** [comment]
Wow that was really fast! Thank you so much!

**Comment by vednoc** [comment]
@SeerLite I'd love to know the values you're using in order to provide good defaults. :smiley:

**Comment by SeerLite** [comment]
Oh sorry, didn't get the github notification!
I'm actually just setting it to 0s, but I'm not sure if that's a good idea. I'm already used to the theme so I know what to expect when I hover over the list, not sure if it'd be the same for new users.

**Comment by vednoc** [comment]
I agree, 0s might not be the best for default values. Let's leave it as-is for now.
