### ISSUE TITLE
Font colour bugs

### ISSUE THREAD

**Issue by fantomasass** [vednoc/dark-whatsapp#139]
The latest Chrome, the latest mode. I’ll continue posting similar stuff. Currently I can’t contribute to the code though.

![Screen 1](https://i.imgur.com/LpqzBho.png)

**Comment by vednoc** [comment]
I'm pretty sure this should be fixed. :thinking: Are you using version `2.3.2`?

**Comment by fantomasass** [comment]
Yes, it’s working now. My bad. I just set up auto-update in Stylus every 1 hour not to miss your fixes.

**Comment by vednoc** [comment]
No worries. Thanks for opening the issue! :smiley:
