### ISSUE TITLE
Font color incorrect in network connection dialog

### ISSUE THREAD

**Issue by NellyWhadsDev** [vednoc/dark-whatsapp#140]
Seems to be missing a style element. May be related to the other font color issue, but I'm not sure.
Have not tested low device battery (phone hasn't been below 15% today) but can update the issue later if that has a similar font color issue.

- **Browser**: Chrome 80.0.3987.149
- **Dark-WhatsApp version**: v2.3.2
- **Additional context**: Load webapp -> disconnect from network
- **Screenshot**:
![image](https://user-images.githubusercontent.com/8030181/77802631-b0da9b80-7051-11ea-873d-ba5b7ab3d700.png)

**Comment by vednoc** [comment]
My phone is at 60% so I'll probably fix the 'low battery' alert tomorrow. This one will be fixed in the next update. :smiley:
