### ISSUE TITLE
video progress bar not showing

### ISSUE THREAD

**Issue by otaviopires** [vednoc/dark-whatsapp#142]
- **Browser**: brave - Version 1.5.115 Chromium: 80.0.3987.149 (Official Build) (64-bit)
- **Dark-WhatsApp version**:2.3.3
- **Additional context**:windows machine
- **Screenshot**:
when I hover the progress bar with the mouse:
![image](https://user-images.githubusercontent.com/1145551/77828767-361a8a80-70fc-11ea-9eeb-32a2ee446bda.png)

without hovering:
![image](https://user-images.githubusercontent.com/1145551/77828774-47fc2d80-70fc-11ea-8baf-bba49755e8f3.png)

**Comment by vednoc** [comment]
I just realized they're using different styles for media inside and outside of WhatsApp. :man_facepalming:

Will be fixed in the next update.
