### ISSUE TITLE
White background when replying to Status updates

### ISSUE THREAD

**Issue by Andrewzz** [vednoc/dark-whatsapp#144]
- **Browser**: Chrome
- **WhatsApp version**: 0.4.2081
- **Dark-WhatsApp version**: 2.3.4
- **Additional context**: When replying to a status update from a contact, the background of the popup window is white.
- **Screenshot**:
![image](https://user-images.githubusercontent.com/161734/78078409-83a72980-7380-11ea-901e-530a1d22e3ee.png)

**Comment by vednoc** [comment]
I think it should be fixed in 856724226779e5c3d977b47845cf2ff89200b509, the fix that is live in the develop branch will be merged into master tomorrow.
