### ISSUE TITLE
Warning that 'person is not in contacts' is not in dark mode

### ISSUE THREAD

**Issue by BenjaminMeijs** [vednoc/dark-whatsapp#146]
- **Browser**: Firefox

- **Whatsapp Language**: Dutch
De afzender staat niet in uw contactenlijst -> The sender is not in your contact list
Rapporteren -> Rapport
Blokkeren -> Block
OK -> OK

- **Additional context**:
I believe the related html is
`<div class="_1JbDr"><div class="_1vDUw"><div class="TYhk9" style="transform: translateY(0px);"><div class="Bixbo">De afzender staat niet in uw contactenlijst</div><div class="_2JCaJ"><div class="rvQu_"><div class="_1WZqU _1sB6s" role="button">Rapporteren</div></div><div class="rvQu_"><div class="_1WZqU _1sB6s" role="button">Blokkeren</div></div><div class="rvQu_"><div class="_1WZqU _1sB6s" role="button">OK</div></div></div></div><div class="_3lztd"></div></div><div class="_1vDUw"><div class="_3lztd"></div></div><div class="_1vDUw"><div class="_3lztd"></div></div><div class="_1vDUw"><div class="_3lztd"></div></div><div class="_1vDUw"><div class="_3lztd"></div></div></div>`

- **Screenshot**:
<img width="625" alt="BugreportPersonisinnotinContacts" src="https://user-images.githubusercontent.com/12033100/78424985-856b3880-7671-11ea-8ada-2d905b044b08.png">

**Comment by vednoc** [comment]
I fixed it yesterday in https://github.com/vednoc/dark-whatsapp/commit/02b490a973fb385e3eac6848b432ebe681292f61; the fix will be live in the next update.

**Comment by BenjaminMeijs** [comment]
Wow nice! It's really cool that you're so active. I love the theme!
