### ISSUE TITLE
Labels tools and quick replies are still white

### ISSUE THREAD

**Issue by tinyCoder32** [vednoc/dark-whatsapp#147]
- **Browser**: Chrome Latest
- **WhatsApp version**: Latest
- **Dark-WhatsApp version**: Latest
- **Additional context**: WA Business, when Labeling a chat, labels toolbar is still white.
- **Screenshot**:

![image](https://user-images.githubusercontent.com/17817239/78726478-c5b10c00-793a-11ea-917e-d5022814bbe9.png)

After fixing, it should look like that:

![image](https://user-images.githubusercontent.com/17817239/78726535-e711f800-793a-11ea-8a4d-a5acae87e818.png)

```
html[dir] ._1HeQs.AYtad {
    background-color: var(--dark);
}
```

There is also another problem, which i reported before in the old versions but it seems that you're not using the business app so you're not aware of the features that broke, when you type a backslash `/` you get quick replies panel, it is still white:
![image](https://user-images.githubusercontent.com/17817239/78726807-9e0e7380-793b-11ea-951c-4cead8121aee.png)

It looks OK however, you don't have to worry about it, sorry it is very difficult to inspect the element and get the classes, the panel disappears when it loses focus.

Thanks.

**Comment by vednoc** [comment]
Will be fixed in the next version.

I don't use WA for Business so most of the things you'll find broken will require additional help. The situation with colors across the entire app will be better once #145 is merged.
