### ISSUE TITLE
Emojis are too big

### ISSUE THREAD

**Issue by jahirfiquitiva** [vednoc/dark-whatsapp#148]
**Describe the change you'd like**:

Hello... This is awesome but emojis are too big for me... Would you mind adding a way to resize them or maybe disabling the custom emojis you put with the theme?

Thanks in advance

**Comment by vednoc** [comment]
I wonder in what sense are custom _emojis_ too big, do you mean _stickers_? :thinking:

You can go back to [default emoji images][0] that are exactly the same size plus have the white background, but it doesn't seem like you're looking for this.


[0]: https://github.com/vednoc/dark-whatsapp/wiki/Configuration#transparent-emojis

**Comment by jahirfiquitiva** [comment]
![Captura de Pantalla 2020-04-08 a la(s) 23 44 29](https://user-images.githubusercontent.com/10360816/78858785-0a987980-79f3-11ea-9e4a-208f687d4e42.png)
![Captura de Pantalla 2020-04-08 a la(s) 23 43 55](https://user-images.githubusercontent.com/10360816/78858791-0c623d00-79f3-11ea-8cde-16e79e885790.png)

Oh, I meant here... I think they are slightly bigger than the default

**Comment by E-RELevant** [comment]
This may be a great suggestion as a feature, but it is important to say that the size of the two images you submitted is exactly the same (`30px`x`30px`), attached below.
Either way, version `2.2013.7` added transparent emojis, so from now on this should be much easier.

![1](https://user-images.githubusercontent.com/20738487/79076209-0b861f80-7d01-11ea-806c-eafb96f1ebb5.jpg)
![2](https://user-images.githubusercontent.com/20738487/79076213-0e811000-7d01-11ea-968e-6b36e3c75b64.jpg)

**Comment by vednoc** [comment]
> Oh, I meant here... I think they are slightly bigger than the default

This was a design decision I had to make a while back. It was sort of lazy, but it looked nice. Thinking about it now, I'll fix the selected state and add the border back, but hover state will still use the scale animation because by default, they're not doing anything. 

P.S. Sorry for delayed reply. I've read the email and forgot to reply in time due to being sidetracked by midterms/coding. :sweat_smile:
