### ISSUE TITLE
New update changed message tails

### ISSUE THREAD

**Issue by nik3348** [vednoc/dark-whatsapp#150]
The first message of a reply will have a tail that tail is white

![image](https://user-images.githubusercontent.com/7848550/80451738-28546100-8957-11ea-9c1b-61770a135183.png)

**Comment by indigo5ive** [comment]
![image](https://user-images.githubusercontent.com/62192447/80456618-40d17500-8971-11ea-8968-0cd4e1cc7ae4.png)
![image](https://user-images.githubusercontent.com/62192447/80456627-45962900-8971-11ea-8aee-1b279d01ec66.png)

Occuring on both receiving and sent messages.

**Comment by E-RELevant** [comment]
The latest WhatsApp Web update to version `2.2017.6` changed the tails to SVGs which is part of the construction work they do for the default dark theme, continuing on the previous version `2.2013.7` that brought us transparent emojis. This is good news for us, as we can influence the color and maintain the original structure of the tail. We will make sure to push an update soon.

**Comment by indigo5ive** [comment]
Beautiful.

**Comment by dngda** [comment]
I fixed this issue by adding `:not([data-icon*="tail-"])` exclusion for the tail svg selector like this
![image](https://user-images.githubusercontent.com/35982346/80484697-5ac78380-8982-11ea-829f-a0e41094dad4.png)
and then add this line 
```
.message-in ._1JfxZ{
    color: var(--msg-l);
}
.message-out ._1JfxZ {
    color: var(--msg-r);
}
```

**Comment by E-RELevant** [comment]
> I fixed this issue by adding `:not([data-icon*="tail-"])` exclusion for the tail svg selector like this

We're trying to avoid using `:not` whenever possible.
The update is live on the `develop` branch and soon will be merged to the `main` branch with some more minor details.

**Comment by simonebortolin** [comment]
This work for me:

span[class][data-icon=tail-in]._1JfxZ > svg > path {
      fill: var(--msg-l) !important;
  }

  span[class][data-icon=tail-out]._1JfxZ > svg > path {
      fill: var(--msg-r) !important
  }

**Comment by vednoc** [comment]
Commit 02291eb has all the necessary fixes, including [various message tail styles][0]. The fix is currently live in the `develop` branch, and I'll merge it into master after I'm done with testing.

Thanks everyone for your suggestions. :tada: 


[0]: https://github.com/vednoc/dark-whatsapp/wiki/Configuration#message-tails
