### ISSUE TITLE
Voice message icons don't signal listened status

### ISSUE THREAD

**Issue by Elsensee** [vednoc/dark-whatsapp#151]
The icons for voice messages don't symbol their listened status anymore. I have screenshotted the class changes, I'm not sure which class is really responsible:

- **Browser**: Firefox 75
- **WhatsApp version**: 2.2017.6
- **Dark-WhatsApp version**: 2.5.0
- **Additional context**: 
- **Screenshot**:
Unlistened status:
![unlistened-wa](https://user-images.githubusercontent.com/1637630/81167677-e8642e00-8f95-11ea-9f21-d104d0da7946.png)
Listened status:
![listened-wa](https://user-images.githubusercontent.com/1637630/81167681-eac68800-8f95-11ea-9a29-9465b0a3dabd.png)

**Comment by vednoc** [comment]
Nice catch! Fix will be out in the next update.

**Comment by Elsensee** [comment]
~I applied the fix and it didn't work for me?~ It does work, but it seems that WhatsApp uses different classes for incoming and outgoing voice messages. Your fix does apply to incoming messages, but for outgoing messages, it should be class `.Zj18s` for unplayed messages, and `.Z8soa` for messages that have been listened to.

However, this doesn't match the slider for outgoing messages (for incoming messages, it does work. Whoa. WhatsApp, wtf :D)

**Comment by vednoc** [comment]
> but for outgoing messages, it should be [...]

For some reason, they are not differentiating between states for outgoing messages. There is no way for me to hack together a solution. I did just found a solution for slider's thumb color for incoming message, which is also a bug on their end.

This whole thing with sliders is just a headache. I can't wait for #145 to get ready so we can use built-in variables.
