### ISSUE TITLE
Add Group Participant is white

### ISSUE THREAD

**Issue by kyle-ds** [vednoc/dark-whatsapp#152]
class="_3fOoY"  ... I think?

![image](https://user-images.githubusercontent.com/51097593/81341536-8fb09600-9066-11ea-9c5b-f1749bce5a86.png)

**Comment by vednoc** [comment]
Yes, good find! Fix will be live in the next update.

**Comment by vednoc** [comment]
Shoot, I forgot to reference this issue in https://github.com/vednoc/dark-whatsapp/commit/8bcd1f1657bcf8feef4a07a03641d8a027d2f0db. :man_facepalming:
