### ISSUE TITLE
Official WhatsApp dark mode

### ISSUE THREAD

**Issue by tinyCoder32** [vednoc/dark-whatsapp#154]
Hey, I just knew that WhatsApp officialy almost finished working on a native dark mode for desktop and web apps.

![image](https://user-images.githubusercontent.com/17817239/82398931-a7235200-9a5c-11ea-8cc7-2775fe126422.png)

It's in development, but you can test it by adding the class name `dark` to the body tag.

![image](https://user-images.githubusercontent.com/17817239/82398475-99210180-9a5b-11ea-8698-00d4ba7393cb.png)

It has transparent emojis finally, it is not customisable though, so we would keep prefering vednoc's work, i thought it might be useful posting this news to the development of this project.

Keep up the nice work.

**Comment by E-RELevant** [comment]
Yes, all of the latest updates, starting mainly with `WhatsApp Web 2.2013.7` were somewhat related to the dark version (adding transparent emojis and so on). You can check the [changelog](https://github.com/vednoc/dark-whatsapp/blob/master/changelog.org#220-2020-02-15-sat) and see that dark class was first introduced @ `Dark WhatsApp v2.2.0`.

Unfortunately, it seems like the native dark app won't be so customizable as well as fix many of the bugs they so call "features" (like RTL `invisible-space` class), which means that vednoc's work is more important and advanced now more than ever.

**Comment by vednoc** [comment]
WhatsApp released their native dark mode today, in the version `2.2027.9` of their Web client.

My plans moving forward are to keep the existing set of features, port missing ones to v3, and get around publishing the v3 of Dark-WhatsApp. I don't have a lot of free time on my hands because of my exams, but some reasonable ETA is the second half of July.

**Comment by Lunchb0ne** [comment]
Thanks for the work!
