### ISSUE TITLE
Unreadable text when there's new update on WhatsApp Web

### ISSUE THREAD

**Issue by thiagobraga** [vednoc/dark-whatsapp#155]
Hi, friend. I'd like to report a bug. When there's a new update for WhatsApp Web, the box showing the update information is unreadable. Could you please fix this issue? :relaxed: 

I copied the HTML but I must have copied something that I overwrote, and after I refreshed the page 🤦🏻‍♂️ Sorry

- **Browser**: Chrome 81.0.4044.138
- **WhatsApp version**: 2.2019.8
- **Dark-WhatsApp version**: 2.6.3
- **Additional context**: when there's new updates on WhatsApp Web
- **Screenshot**:
![image](https://user-images.githubusercontent.com/993684/82446104-64717200-9a7c-11ea-9f82-5b00d036f9b0.png)

**Comment by vednoc** [comment]
This is something that @E-RELevant had as well some time ago. Unfortunately, there is no way to fix this without selectors. I'm pretty sure it's going to be fine once #145 is merged in, but that will take _some_ more time, I think. :frowning: 

Funnily enough, I remember seeing `2.2021.2` last night and they went back to `2.2019.8` today? I'm not entirely sure what happened, but I seem to have gone back to the old version too.

**Comment by thiagobraga** [comment]
I managed to capture the HTML snippet regarding the update. The element is a sibling of the header element. I attached a screenshot.

``` html
<span class="m6ZEb">
  <div class="_1Wk6A">
    <div class="_3YewW _31v_P _2Ptrm">
      <div class="_2fJ2T">
        <span data-icon="alert-update" class="">
          <svg xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 48 48" width="48" height="48">
            <path fill="currentColor"
              d="M24.154 2C11.919 2 2 11.924 2 24.165S11.919 46.33 24.154 46.33s22.154-9.924 22.154-22.165S36.389 2 24.154 2zm7.547 21.037h-6.738l3.08-3.08c-1.059-1.059-2.406-1.733-4.043-1.733-3.176 0-5.775 2.599-5.775 5.775 0 3.177 2.599 5.776 5.775 5.776 2.503 0 4.62-1.637 5.391-3.85h2.021c-.866 3.273-3.85 5.776-7.412 5.776-4.235 0-7.701-3.465-7.701-7.701 0-4.235 3.465-7.701 7.701-7.701 2.118 0 4.043.866 5.391 2.31l2.31-2.31v6.738z">
            </path>
          </svg>
        </span>
      </div>
      <div class="l2BEH">
        <div class="U0cj3">Atualização disponível</div>
        <div class="_21zbN">
          <span class="_43SdW">
            <span class="B-eJw">Clique para atualizar o WhatsApp</span>
            <span
              data-icon="chevron-right-text" class="_3ORld">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 8 12"
                width="8" height="12">
                <path fill="currentColor" d="M2.173 1l4.584 4.725-4.615 4.615-1.103-1.103 3.512-3.512L1 2.173 2.173 1z">
                </path>
              </svg>
            </span>
          </span>
        </div>
      </div>
    </div>
  </div>
</span>
``` 

<details>
  <summary><b>Screenshot</b></summary>
  <img src="https://user-images.githubusercontent.com/993684/83644820-13877080-a588-11ea-80c6-e357754ac82b.png" />
</details>

**Comment by vednoc** [comment]
That's the one. Great job @thiagobraga! 🎉
