### ISSUE TITLE
The text "Update available ..." is in a dark color, so I can't see clearly

### ISSUE THREAD

**Issue by petrustjoi** [vednoc/dark-whatsapp#157]
- **Browser**: _Google Chrome Version 83.0.4103.61 (Official Build) (64-bit)_
- **WhatsApp version**: _Web WhatsApp Version 2.2021.4_
- **Dark-WhatsApp version**: _Dark-WhatsApp Lite v2.7.0 — May 23rd, 2020_
- **Additional context**: The color is also black and difficult to read
- **Screenshot**:
     ![a](https://user-images.githubusercontent.com/66345222/83590987-25194a00-a581-11ea-84ba-4e1da2919bed.JPG)

**Notification Says:**
==============================
     Update available
     Click to update WhatsApp >

**Stylus Extension Detect:**
==============================
Type | Prefix | : | Suffix | Explanation
-- | -- | -- | -- | --
warning | 50 | : | 5 | Duplicate property '--message' found.
warning | 55 | : | 7 | Unknown property 'scrollbar-width'.
warning | 119 | : | 5 | Unknown property 'scrollbar-color'.
warning | 269 | : | 5 | Expected end of value but found '" \A\A "'.
warning | 814 | : | 7 | Expected end of value but found '0'.
warning | 1358 | : | 5 | Expected 'none \| matrix() \| translate() \| translateX() \| translateY() \| scale() \| scaleX() \| scaleY(...
warning | 1592 | : | 5 | Expected end of value but found ','.
warning | 2247 | : | 5 | Expected end of value but found ','.

Sincerely,
petrustjoi :kissing_heart:

**Comment by vednoc** [comment]
Same as #155.

I'm unable to fix it without HTML snippet of that entire area; I think the parent element is `.m6ZEb` but that's just my guess as this is where other notifications go. I've been on `2.2021.4` update for over a week now, so it's unlikely that I'm going to get this notification.

> Stylus Extension Detect

Linter warnings, you can turn them off, more in-depth [explanation here][0].

[0]: https://github.com/vednoc/dark-whatsapp/wiki/FAQ#why-are-there-so-many-errors-on-the-style-edit-page
