### ISSUE TITLE
New version released (v2.2023.2) and guess what?

### ISSUE THREAD

**Issue by UnderEu** [vednoc/dark-whatsapp#158]
- **Browser**: Firefox 77.0.1 (macOS)
- **WhatsApp version**: 2.2023.2
- **Dark-WhatsApp version**: 2.8.0
- **Additional context**: Nothing in addition
- **Screenshot**: ![Screen Shot 2020-06-03 at 16 29 08](https://user-images.githubusercontent.com/16519758/83680584-89570080-a5b7-11ea-81b2-299a2e9bfdbd.png)

**Comment by vednoc** [comment]
Oh shoot, I hope they're not rolling it out immediately to everyone. I'll be working on merging #145 ASAP and worry about procedural color generation (that Erel and I have been working on) as well as other features later.

**Comment by vednoc** [comment]
Seems to be only available to Beta testers, and I'm sure I _don't_ have beta version of WhatsApp on my phone, so it makes no sense to show it to me.

For the time being, this is a temporary solution if you see this in DevTools:
``` html
<html class="js..." dir="LTR" loc="en" x-wa-beta="1" lang="en">
```
You're able to go back to the previous version by refreshing the page a few times.

**Comment by snoopdoge93** [comment]
dammit.. it blinded me now

**Comment by fid3lito** [comment]
I can't see anything send help

**Comment by kyle-ds** [comment]
I don't think it's beta related. I'm on Ferdi 5.5.0 and i'm also blinded by the light. Revved up... i'll stop.

**Comment by indierodo** [comment]
I can't find any "beta" here:

`<html class="js..." dir="LTR" loc="en" lang="es">`

I'll wait for an update. Thank you for your hard work! Let me know if I can help.

**Comment by vednoc** [comment]
> I can't find any "beta" here:

Seems like the "beta" lasted for 24 hours, welp.

--
Quick update, it's almost ready! Here's a preview:

![image](https://user-images.githubusercontent.com/18245694/83840134-173d0380-a6fe-11ea-839b-027abc4785d4.png)

**Comment by quickishfm** [comment]
![image](https://user-images.githubusercontent.com/47328894/83875687-7404e200-a72f-11ea-9ae2-81df899f7f1e.png)
Replies are also in white here, is this related to this issue?

**Comment by vednoc** [comment]
>  Replies are also in white here, is this related to this issue?

Yes, it's already fixed and the update will be live right after I'm done writing [changelog][0] and converting it to CSS format for Franz/Ferdi/etc.

[0]: https://github.com/vednoc/dark-whatsapp/blob/master/changelog.org

**Comment by vednoc** [comment]
Update from Stylus' manage page or reinstall the userstyle to get the latest version. 😊
