### ISSUE TITLE
New whatsapp web update and css errors

### ISSUE THREAD

**Issue by Katakurinna** [vednoc/dark-whatsapp#159]
- **Browser**:  Chrome 83.0.4103.97 (Build oficial) (64 bits)
- **WhatsApp version**: 2.20.172
- **Dark-WhatsApp version**:  2.8.0
- **Additional context**:  
- **Screenshot**:
![Whatsapp error](https://user-images.githubusercontent.com/43810296/83811245-bd1a4f00-a6b9-11ea-9427-8f13257976e1.png)

**Comment by Katakurinna** [comment]
And here 
![image](https://user-images.githubusercontent.com/43810296/83811354-f2bf3800-a6b9-11ea-83a6-ac0401db3f9e.png)
![image](https://user-images.githubusercontent.com/43810296/83811377-fce13680-a6b9-11ea-9045-87b86dca9a64.png)

**Comment by lihuelworks** [comment]
Same thing here:

![image](https://user-images.githubusercontent.com/49965980/83821897-ffd22c00-a6a5-11ea-8114-2b93117b7dbf.png)

**Comment by ArianCalabrese** [comment]
Same here, i tried updating but nothing changed.

**Comment by vednoc** [comment]
Same as #158. 

Update is on the way, and temporary solution is available in the comments.
