### ISSUE TITLE
Compact mode is broken! Help, please!

### ISSUE THREAD

**Issue by abraaorosa** [vednoc/dark-whatsapp#160]
**Describe the change you'd like**:

➜ Reactivate compact mode.
➜ It would be very interesting to use the colors of the whatsapp application in dark mode.

- **Browser**:
Firefox Browser Developer Edition 78.0b3 (64-bits)

- **WhatsApp version**:
Versão 2.2023.2

- **Dark-WhatsApp version**:
Dark-WhatsApp v2.9.0

- **Additional context**:
I read in the logs today that this new update changed several parameters of the CSS code, my style worked perfectly, including the colors. Unfortunately everything is subject to change and in this case it was very fast. There is a feature, which for me is the best of all, I ask that if possible, fix it as soon as possible! Please!
Compact mode is no longer working! This is my only request.

- **Screenshot**:
![image](https://user-images.githubusercontent.com/11440555/83904748-cdbcda80-a736-11ea-8521-172850e9a155.png)

**Comment by vednoc** [comment]
I'm glad that you've read the changelog!

Compact mode is one of the first things that I'll be working on tomorrow since my time ran out for today. It should make it into next update, but I'll have figure out new selectors and that can take _some_ time.

**Comment by abraaorosa** [comment]
Wow!! Thank you very much for the quick response! I'm glad this feature is on the priority list! I'm anxious!

**Comment by vednoc** [comment]
Just got it reimplemented! I'll have to test it in Chromium and it'll be ready in the next update. 😊 

Quick preview:

![image](https://user-images.githubusercontent.com/18245694/83950648-a9dbc080-a82c-11ea-817d-c63857978d48.png)

**Comment by abraaorosa** [comment]
Wow! First of all, I would like to thank you! I can't live without that extension anymore! Thank you!

**Comment by vednoc** [comment]
Hey @abraaorosa, you are welcome! I'm glad you find it that useful; it's really one of essential features. 😊
