### ISSUE TITLE
Would it be possible to customize this in a node environment?

### ISSUE THREAD

**Issue by amanharwara** [vednoc/dark-whatsapp#161]
### I would like to be able do the following

1. Fetch the customizable version of the theme in a NodeJS/Electron environment.
2. Modify the colors/variables
3. Create a frontend for it so users can create their own color schemes.

### Additional context

I want to use this as a base theme so I can let users of my [app](https://github.com/amanharwara/altus) can create their own color schemes. Hence, I would like to know if this is possible.

**Comment by vednoc** [comment]
It should be!

Initially my goal with `whatsapp.sh` was to include some sort of template that would have minimal UserCSS metadata (not needed, just so curious people can see where it comes from), and all of the stylus-lang variables.

Stylus' configuration menu is just a pretty front-end for what's underneath. You can see what compiling manually looks like [here][0]. There are many ways to go about implementing this in your app. With aforementioned script, I wanted to cut all the text from `wa.user.styl` until `@-moz-document...` line, concatenate it with metadata, and then compile it using stylus-lang NPM package.

Right now, I have some sort of template. Occasionally I use a few regex commands to convert it from UserCSS to raw format and it works pretty good except for `select`/`range` variables.

[0]: https://github.com/vednoc/dark-whatsapp/wiki/FAQ#how-to-convert-stylus-lang-to-css

**Comment by vednoc** [comment]
> so I can let users of my app can create their own color schemes
Adding to this, it's even easier now that we have a color generator. You'll just need to worry about three variables for background, foreground, and accent colors. You could even override them here, as that might be the easiest way to go about it:
```styl
BG = next_bg
FG = next_fg
AC = next_ac
```

**Comment by amanharwara** [comment]
Is there a way to automate the process of replacing the UserCSS metadata with Stylus variables?

**Comment by amanharwara** [comment]
Also, could you explain what the bash script does? I don't really understand the commands.

**Comment by vednoc** [comment]
> Is there a way to automate the process of replacing the UserCSS metadata with Stylus variables?

I think that Stylus uses their [openstyles/usercss-meta][0] library, but I'm not entirely sure how it works as I haven't spent a lot of time looking into the code. 

> Also, could you explain what the bash script does?

It takes `wa.user.css` file, removes all of the lines from the top including `@-moz-document...` line, removes the very last line, and also removes the two leading whitespace characters. What you're left with is [this][1].

[0]: https://github.com/openstyles/usercss-meta
[1]: https://github.com/dcferreira/franz-themes/blob/73a83bea77f5db2b0898322c479074f1e0282ab9/whatsapp/darkmode.css

**Comment by amanharwara** [comment]
Thank you very much! It ended up being quite easy to do.
And thanks for this great theme!

**Comment by vednoc** [comment]
I'm glad to hear that! It's super nice to see my work being used in other projects.

By the way, I just realized I forgot to star your repository, and it's also my 100th star. 😄 🎉
