### ISSUE TITLE
Blue tick visibility

### ISSUE THREAD

**Issue by itsharsh** [vednoc/dark-whatsapp#162]
As of now, the blue tick's visibility is quite dull,
![image](https://user-images.githubusercontent.com/14810684/83909870-359b1180-a787-11ea-966c-62edaf9ddaf9.png)

It is hard to distinguish with the message background colour

**Comment by vednoc** [comment]
Thanks for pointing that out! I'll have to do a few accessibility tests and improve rules for color generator.
