### ISSUE TITLE
Accent adjustments

### ISSUE THREAD

**Issue by nischalon10** [vednoc/dark-whatsapp#163]
**Describe the change you'd like**:
I have used the previous version and loved so many things
I could change the accent color but cannot now.
The square-edged text boxes were better.
So many other things were better than they are now.
Please bring them back

**Additional context**:

**Comment by vednoc** [comment]
> Please bring them back

Take a minute to read [changelog][0], I wrote about old features there.

>  I could change the accent color but cannot now.

You can do it, it's just using the new setting. This one, to be precise: `[Dev]: Base accent color`


[0]: https://github.com/vednoc/dark-whatsapp/blob/master/changelog.org
