### ISSUE TITLE
Style applies to non-WhatsApp websites

### ISSUE THREAD

**Issue by mahmoudhossam** [vednoc/dark-whatsapp#164]
- **Browser**: Firefox 77.0.1
- **WhatsApp version**: 2.2023.2
- **Dark-WhatsApp version**: 2.10.0

Dark-WhatsApp applies to websites other than WhatsApp, here's a screenshot of it applying to Github.

![image](https://user-images.githubusercontent.com/619795/83967562-1a352100-a8c3-11ea-9864-254d8b5fd689.png)

**Comment by shevernitskiy** [comment]
Confirm. 121-194 lines placed before @-moz-document domain. It makes style global.

**Comment by vednoc** [comment]
> Confirm. 121-194 lines placed before @-moz-document domain. It makes style global.

Nope, these lines don't add any new CSS rules, they're only used for stylus-lang helpers. It's actually [this line][0] that is causing the problem. It will be fixed in the next update.

[0]: https://github.com/vednoc/dark-whatsapp/blob/f2c7ee2383bcc117b4f69129c0719c71f5511525/wa.user.styl#L1098
