### ISSUE TITLE
Any way of you reducing that delay from choosing the emoji (using the colon) and being able to sending it?

### ISSUE THREAD

**Issue by vassilyzaitsev** [vednoc/dark-whatsapp#170]
**Describe the change you'd like**:

I would like to decrease this delay or eliminate it.

**Additional context**:

Currently, when I want to select an emoji, I press colon (:) and then I get to choose... But there's a "security" config blocking me from sending (it) right away... I feel like I have to wait a second or so...

Thanks.

**Comment by vednoc** [comment]
You have to insert two or more characters like shown in the gif, and that can't be changed with CSS.

However, if you'd like the bar to show up instantly, I can look into that.

![peek-emojis](https://user-images.githubusercontent.com/18245694/85899713-c0a77e80-b7fe-11ea-9684-d0c0b69c16f6.gif)

**Comment by vassilyzaitsev** [comment]
> However, if you'd like the bar to show up instantly, I can look into that.

It's not really what I want... 
I was talking about the fact that you can't select an emoji, press enter, and then quickly press enter again, to send....
There's this delay, blocking you from, sending enter repeatedly... A kind of "max key presses per second" or something..


You can see here how I have to press "enter" at least 4 times to send an emoji, or, wait a bit... But I can't send it right away:
[https://i.imgur.com/SLK1NkJ.gif](url)

**Comment by vednoc** [comment]
Sorry for replying late!

I had a quick look at the bundled JS and tried debugging it, but I can't tell what or why this is the case for emojis. It might be a bug since you _can_ send text messages instantly in this way. Have you tried reporting this directly to WA?

**Comment by vassilyzaitsev** [comment]
> Sorry for replying late!

No problem. I'm just glad you tried. haha

> I had a quick look at the bundled JS and tried debugging it, but I can't tell what or why this is the case for emojis. It might be a bug since you _can_ send text messages instantly in this way. 

I don't know anything about JS but I was having a look at the events for this class and it looks that this function "preventDefault" might have something to do with it... 

![07-01-2020 - 16h40m26s (138)](https://user-images.githubusercontent.com/35409978/86285340-47f74800-bb99-11ea-8aca-84d618c2ffac.png)

Because there's this other method for sending emojis, and this one have no blocking/delay:
![image](https://user-images.githubusercontent.com/35409978/86285838-34001600-bb9a-11ea-8b3d-74913db2df53.png)

And this function "preventDefault" is not called in this class.

> Have you tried reporting this directly to WA?

Do you think they might help? I didn't report to them because I didn't thought it was a bug. It looks as if they are trying to avoid accidental messages. Silly, but intentional 😅😅. Imma try that though. And I'm sorry if this is too much work.

**Comment by vednoc** [comment]
> I was having a look at the events for this class

I was doing the same thing. Unfortunately, my JS skills aren't that great either.

> this function "preventDefault" might have something to do with it

I don't think that's the one, but it very well could be! You can see an example for it as well as other things here:
https://devdocs.io/dom/event/preventdefault

If you'd like to debug some more, I think this element is where you should start: `<div class="_3FRCZ copyable-text selectable-text" data-tab="1" dir="ltr" spellcheck="true" contenteditable="true"></div>`
It has a bunch of other events to it, and my computer runs out of memory half the time while trying to step into each call with the debugger. 😦 

> Do you think they might help?

Just _maybe_. I know that Erel reported multiple issues, and the one that's the most critical (RTL text) is still broken months later, and I find it unacceptable for a chat application to have a messed up text orientation.

**Comment by vassilyzaitsev** [comment]
I think I'm gonna look for a way to stop this function via script, like for Greasemonkey or, the one I use, Tampermonkey.

Thanks for everything. 🤙 🤙

**Comment by E-RELevant** [comment]
The issue seems to have come to an end.
