### ISSUE TITLE
Whatsapp update and css errors

### ISSUE THREAD

**Issue by lihuelworks** [vednoc/dark-whatsapp#171]
- **Browser**:
Version 83.0.4103.116 (Official Build) (64-bit)
- **WhatsApp Web version**:
Version 2.2027.9
- **Dark-WhatsApp version**:
2.15.0
- **Additional context**:
Whatsapp is at it again. Maybe they've changed something about the DOM, because somethink akin to #159 happened again, that being "white sections" around the dark elements of the style.
- **Screenshot**:
![Screenshot_15](https://user-images.githubusercontent.com/49965980/86201043-ca015580-bb34-11ea-8ddb-d6b63ec9f982.png)
![Screenshot_14](https://user-images.githubusercontent.com/49965980/86201047-cc63af80-bb34-11ea-9beb-7553ad1a3ab7.png)

Edit: Updated the version of WhatsApp _Web_; bug template needs to be updated.

**Comment by diyachan** [comment]
WhatsApp web just rolled out its own dark theme, i think the theme should now target that instead of the default light one
![image](https://user-images.githubusercontent.com/7719971/86207740-58a7be00-bb99-11ea-883d-a78cb5cbd29d.png)

**Comment by lihuelworks** [comment]
Seems like it. maybe they touched the site to include the new dark design. This is how it looks by choosing "Dark". The same masking occurs, where parts of Whatsapp's theme mix with Vendoc's theme. For the record, I like Vendoc's better.

![Screenshot_16](https://user-images.githubusercontent.com/49965980/86208972-f377ac80-bb47-11ea-9b35-5ec35fddb3c6.png)
![Screenshot_17](https://user-images.githubusercontent.com/49965980/86208975-f4104300-bb47-11ea-85fa-561094b3c9e4.png)

**Comment by vednoc** [comment]
They've added 32 _new_ variables. 🙃 I'll go over them and release a hotfix pretty soon; hopefully they didn't break custom features of DWA.

--
As per usual, you can refresh the page a few times to go back to `v2.2025.6` while WA Web is in the "beta" state. This will very likely end in less than 24 hours.
