### ISSUE TITLE
Error when rendering with Stylus package

### ISSUE THREAD

**Issue by amanharwara** [vednoc/dark-whatsapp#172]
- **Browser**: Electron 9.1.0 / Chromium 83.0.4103.119
- **WhatsApp Web version**: 2.2027.10
- **Dark-WhatsApp version**: 2.16.1
- **Screenshot**:
![2020-07-11 19_39_43-Window](https://user-images.githubusercontent.com/8348101/87225952-3a537680-c380-11ea-9d70-7907da08c41c.png)

- **Additional context**:
Hey! You might remember me from issue #161.
I don't know when exactly this started happening, but when trying to compile the latest `.styl` file using the **Stylus** package, it errors out.
Looking at the error, it looks like the identifier `BG` is being passed into some stylus function that requires an rgba/hsla value.
Any clue why this might be happening?

**Comment by amanharwara** [comment]
Same thing happens when trying to compile it in the terminal with the global `stylus` package.

Here's the terminal output:

<details>
<summary>Terminal Output</summary>
<pre>
(node:7516) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7516) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:7516) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:7516) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:7516) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:7516) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
C:\Users\aman\AppData\Roaming\npm\node_modules\stylus\bin\stylus:685
              throw err;
              ^

Error: C:/Users/aman/AppData/Roaming/npm/node_modules/stylus/lib/functions/index.styl:133:3
   129|
   130| // lighten by the given amount
   131|
   132| lighten(color, amount)
   133|   adjust(color, 'lightness', amount)
----------^
   134|
   135| // decrease opacity by amount
   136|

TypeError: expected rgba or hsla, but got ident:darker
    at ":root " (wa.styl:1751:5)

    at Object.exports.assertColor (C:\Users\aman\AppData\Roaming\npm\node_modules\stylus\lib\utils.js:255:13)
    at Evaluator.adjust (C:\Users\aman\AppData\Roaming\npm\node_modules\stylus\lib\functions\adjust.js:14:9)
    at Evaluator.invokeBuiltin (C:\Users\aman\AppData\Roaming\npm\node_modules\stylus\lib\visitor\evaluator.js:1054:30)
    at Evaluator.visitCall (C:\Users\aman\AppData\Roaming\npm\node_modules\stylus\lib\visitor\evaluator.js:516:16)
    at Evaluator.Visitor.visit (C:\Users\aman\AppData\Roaming\npm\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (C:\Users\aman\AppData\Roaming\npm\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitExpression (C:\Users\aman\AppData\Roaming\npm\node_modules\stylus\lib\visitor\evaluator.js:644:26)
    at Evaluator.Visitor.visit (C:\Users\aman\AppData\Roaming\npm\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (C:\Users\aman\AppData\Roaming\npm\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.eval (C:\Users\aman\AppData\Roaming\npm\node_modules\stylus\lib\visitor\evaluator.js:1238:23) {
  lineno: 133,
  column: 3,
  filename: 'C:/Users/aman/AppData/Roaming/npm/node_modules/stylus/lib/functions/index.styl',
  stylusStack: '    at ":root " (wa.styl:1751:5)',
  input: 'called-from = ()\n' +
    '\n' +
    'vendors = moz webkit o ms official\n' +
    '\n' +
    '// stringify the given arg\n' +
    '\n' +
    '-string(arg)\n' +
    "  type(arg) + ' ' + arg\n" +
    '\n' +
    '// require a color\n' +
    '\n' +
    'require-color(color)\n' +
    "  unless color is a 'color'\n" +
    "    error('RGB or HSL value expected, got a ' + -string(color))\n" +
    '\n' +
    '// require a unit\n' +
    '\n' +
    'require-unit(n)\n' +
    "  unless n is a 'unit'\n" +
    "    error('unit expected, got a ' + -string(n))\n" +
    '\n' +
    '// require a string\n' +
    '\n' +
    'require-string(str)\n' +
    "  unless str is a 'string' or str is a 'ident'\n" +
    "    error('string expected, got a ' + -string(str))\n" +
    '\n' +
    '// Math functions\n' +
    '\n' +
    "abs(n) { math(n, 'abs') }\n" +
    'min(a, b) { a < b ? a : b }\n' +
    'max(a, b) { a > b ? a : b }\n' +
    '\n' +
    '// Trigonometrics\n' +
    "PI = -math-prop('PI')\n" +
    '\n' +
    'radians-to-degrees(angle)\n' +
    '  angle * (180 / PI)\n' +
    '\n' +
    'degrees-to-radians(angle)\n' +
    '  angle * (PI / 180)\n' +
    '\n' +
    'sin(n)\n' +
    "  n = unit(n) == 'deg' ? degrees-to-radians(unit(n, '')) : unit(n, '')\n" +
    "  round(math(n, 'sin'), 9)\n" +
    '\n' +
    'cos(n)\n' +
    "  n = unit(n) == 'deg' ? degrees-to-radians(unit(n, '')) : unit(n, '')\n" +
    "  round(math(n, 'cos'), 9)\n" +
    '\n' +
    '// Rounding Math functions\n' +
    '\n' +
    'ceil(n, precision = 0)\n' +
    '  multiplier = 10 ** precision\n' +
    "  math(n * multiplier, 'ceil') / multiplier\n" +
    '\n' +
    'floor(n, precision = 0)\n' +
    '  multiplier = 10 ** precision\n' +
    "  math(n * multiplier, 'floor') / multiplier\n" +
    '\n' +
    'round(n, precision = 0)\n' +
    '  multiplier = 10 ** precision\n' +
    "  math(n * multiplier, 'round') / multiplier\n" +
    '\n' +
    '// return the sum of the given numbers\n' +
    '\n' +
    'sum(nums)\n' +
    '  sum = 0\n' +
    '  sum += n for n in nums\n' +
    '\n' +
    '// return the average of the given numbers\n' +
    '\n' +
    'avg(nums)\n' +
    '  sum(nums) / length(nums)\n' +
    '\n' +
    '// return a unitless number, or pass through\n' +
    '\n' +
    'remove-unit(n)\n' +
    '  if typeof(n) is "unit"\n' +
    '    unit(n, "")\n' +
    '  else\n' +
    '    n\n' +
    '\n' +
    '// convert a percent to a decimal, or pass through\n' +
    '\n' +
    'percent-to-decimal(n)\n' +
    '  if unit(n) is "%"\n' +
    '    remove-unit(n) / 100\n' +
    '  else\n' +
    '    n\n' +
    '\n' +
    '// check if n is an odd number\n' +
    '\n' +
    'odd(n)\n' +
    '  1 == n % 2\n' +
    '\n' +
    '// check if n is an even number\n' +
    '\n' +
    'even(n)\n' +
    '  0 == n % 2\n' +
    '\n' +
    '// check if color is light\n' +
    '\n' +
    'light(color)\n' +
    '  lightness(color) >= 50%\n' +
    '\n' +
    '// check if color is dark\n' +
    '\n' +
    'dark(color)\n' +
    '  lightness(color) < 50%\n' +
    '\n' +
    '// desaturate color by amount\n' +
    '\n' +
    'desaturate(color, amount)\n' +
    "  adjust(color, 'saturation', - amount)\n" +
    '\n' +
    '// saturate color by amount\n' +
    '\n' +
    "saturate(color = '', amount = 100%)\n" +
    "  if color is a 'color'\n" +
    "    adjust(color, 'saturation', amount)\n" +
    '  else\n' +
    '    unquote( "saturate(" + color + ")" )\n' +
    '\n' +
    '// darken by the given amount\n' +
    '\n' +
    'darken(color, amount)\n' +
    "  adjust(color, 'lightness', - amount)\n" +
    '\n' +
    '// lighten by the given amount\n' +
    '\n' +
    'lighten(color, amount)\n' +
    "  adjust(color, 'lightness', amount)\n" +
    '\n' +
    '// decrease opacity by amount\n' +
    '\n' +
    'fade-out(color, amount)\n' +
    '  color - rgba(black, percent-to-decimal(amount))\n' +
    '\n' +
    '// increase opacity by amount\n' +
    '\n' +
    'fade-in(color, amount)\n' +
    '  color + rgba(black, percent-to-decimal(amount))\n' +
    '\n' +
    '// spin hue by a given amount\n' +
    '\n' +
    'spin(color, amount)\n' +
    '  color + unit(amount, deg)\n' +
    '\n' +
    '// mix two colors by a given amount\n' +
    '\n' +
    'mix(color1, color2, weight = 50%)\n' +
    '  unless weight in 0..100\n' +
    '    error("Weight must be between 0% and 100%")\n' +
    '\n' +
    '  if length(color1) == 2\n' +
    '    weight = color1[0]\n' +
    '    color1 = color1[1]\n' +
    '\n' +
    '  else if length(color2) == 2\n' +
    '    weight = 100 - color2[0]\n' +
    '    color2 = color2[1]\n' +
    '\n' +
    '  require-color(color1)\n' +
    '  require-color(color2)\n' +
    '\n' +
    "  p = unit(weight / 100, '')\n" +
    '  w = p * 2 - 1\n' +
    '\n' +
    '  a = alpha(color1) - alpha(color2)\n' +
    '\n' +
    '  w1 = (((w * a == -1) ? w : (w + a) / (1 + w * a)) + 1) / 2\n' +
    '  w2 = 1 - w1\n' +
    '\n' +
    '  channels = (red(color1) red(color2)) (green(color1) green(color2)) (blue(color1) blue(color2))\n' +
    '  rgb = ()\n' +
    '\n' +
    '  for pair in channels\n' +
    '    push(rgb, floor(pair[0] * w1 + pair[1] * w2))\n' +
    '\n' +
    '  a1 = alpha(color1) * p\n' +
    '  a2 = alpha(color2) * (1 - p)\n' +
    '  alpha = a1 + a2\n' +
    '\n' +
    '  rgba(rgb[0], rgb[1], rgb[2], alpha)\n' +
    '\n' +
    '// invert colors, leave alpha intact\n' +
    '\n' +
    "invert(color = '')\n" +
    "  if color is a 'color'\n" +
    '    rgba(#fff - color, alpha(color))\n' +
    '  else\n' +
    '    unquote( "invert(" + color + ")" )\n' +
    '\n' +
    '// give complement of the given color\n' +
    '\n' +
    'complement( color )\n' +
    '  spin( color, 180 )\n' +
    '\n' +
    '// give grayscale of the given color\n' +
    '\n' +
    "grayscale( color = '' )\n" +
    "  if color is a 'color'\n" +
    '    desaturate( color, 100% )\n' +
    '  else\n' +
    '    unquote( "grayscale(" + color + ")" )\n' +
    '\n' +
    '// mix the given color with white\n' +
    '\n' +
    'tint( color, percent )\n' +
    '  mix( white, color, percent )\n' +
    '\n' +
    '// mix the given color with black\n' +
    '\n' +
    'shade( color, percent )\n' +
    '  mix( black, color, percent )\n' +
    '\n' +
    '// return the last value in the given expr\n' +
    '\n' +
    'last(expr)\n' +
    '  expr[length(expr) - 1]\n' +
    '\n' +
    '// return keys in the given pairs or object\n' +
    '\n' +
    'keys(pairs)\n' +
    '  ret = ()\n' +
    "  if type(pairs) == 'object'\n" +
    '    for key in pairs\n' +
    '      push(ret, key)\n' +
    '  else\n' +
    '    for pair in pairs\n' +
    '      push(ret, pair[0]);\n' +
    '  ret\n' +
    '\n' +
    '// return values in the given pairs or object\n' +
    '\n' +
    'values(pairs)\n' +
    '  ret = ()\n' +
    "  if type(pairs) == 'object'\n" +
    '    for key, val in pairs\n' +
    '      push(ret, val)\n' +
    '  else\n' +
    '    for pair in pairs\n' +
    '      push(ret, pair[1]);\n' +
    '  ret\n' +
    '\n' +
    '// join values with the given delimiter\n' +
    '\n' +
    'join(delim, vals...)\n' +
    "  buf = ''\n" +
    '  vals = vals[0] if length(vals) == 1\n' +
    '  for val, i in vals\n' +
    '    buf += i ? delim + val : val\n' +
    '\n' +
    '// add a CSS rule to the containing block\n' +
    '\n' +
    '// - This definition allows add-property to be used as a mixin\n' +
    '// - It has the same effect as interpolation but allows users\n' +
    '//   to opt for a functional style\n' +
    '\n' +
    'add-property-function = add-property\n' +
    'add-property(name, expr)\n' +
    '  if mixin\n' +
    '    {name} expr\n' +
    '  else\n' +
    '    add-property-function(name, expr)\n' +
    '\n' +
    'prefix-classes(prefix)\n' +
    '  -prefix-classes(prefix, block)\n' +
    '\n' +
    '// Caching mixin, use inside your functions to enable caching by extending.\n' +
    '\n' +
    '$stylus_mixin_cache = {}\n' +
    'cache()\n' +
    "  $key = (current-media() or 'no-media') + '__' + called-from[0] + '__' + arguments\n" +
    '  if $key in $stylus_mixin_cache\n' +
    '    @extend {"$cache_placeholder_for_" + $stylus_mixin_cache[$key]}\n' +
    "  else if 'cache' in called-from\n" +
    '    {block}\n' +
    '  else\n' +
    '    $id = length($stylus_mixin_cache)\n' +
    '\n' +
    '    &,\n' +
    '    /$cache_placeholder_for_{$id}\n' +
    '      $stylus_mixin_cache[$key] = $id\n' +
    '      {block}\n' +
    '\n' +
    '// Percentage function to convert a number, e.g. ".45", into a percentage, e.g. "45%"\n' +
    '\n' +
    'percentage(num)\n' +
    "  return unit(num * 100, '%')\n" +
    '\n' +
    '// Returns the position of a `value` within a `list`\n' +
    '\n' +
    'index(list, value)\n' +
    '  for val, i in list\n' +
    '    return i if val == value\n'
}
</pre>
</details>

**Comment by vednoc** [comment]
It does look like something is wrong with the BG color. That could be because of many reasons, and other errors unfortunately aren't all that helpful. Try to compare or replace your changes with this template:

<details>
<summary>Show code</summary>

```styl
v3         = 1
theme      = 'custom'
next_bg    = #1f232a
next_fg    = #eeeeee
next_ac    = #7289da
next_bg_a  = 0%
ow_imsg    = 0
next_imsg  = #16191e
ow_omsg    = 0
next_omsg  = #3b4250
ui_font    = 'font_name'
radius-g   = 4px
radius-i   = 24px
radius-a   = 50%
app_width  = 1396px
fullscreen = 0
app_c_m    = 1
app_c_m_w  = 720px
app_c_m_h  = 0.6s
app_c_m_d  = 1.2s
chat_b_c   = 0
app_c_h    = 1
alerts     = 'show'
app_image  = 'bg-high'
image_url  = url('https://images.unsplash.com/photo-1434569117012-ce134ee1a088?fit=crop&w=1280&h=720&q=80')
bg_opacity = 0.4
bg_blur    = 0px
bg_hue     = 320deg
bg_invert  = 0
bg_size    = cover
bg_pos     = center
bg_rep     = no-repeat
emoji_o    = 0.8
ff_scroll  = 1
chat_bg    = 1
chat_image = url('https://web.whatsapp.com/img/bg-chat-tile_9e8a2898faedb7db9bf5638405cf81ae.png')
chat_bg_o  = 0.15
chat_bg_iv = 0.6
chat_bg_s  = initial
chat_bg_p  = top left
chat_bg_r  = repeat
rtl_header = 1
rtl_format = 1
c_g_c      = 1
_dark      = #1f232a
_darken    = #252A33
darker     = #333943
light      = #e9e9e9
lighter    = #a1a1a1
accent     = #7289da
yellow     = #e5c512
orange     = #df4b16
red        = #dc322f
magenta    = #f33682
violet     = #6c71c4
blue       = #268bd2
cyan       = #2aa198
green      = #859900
white      = #ffffff
sh         = #00000025
sh-h       = #00000035
```
</details>

**Comment by amanharwara** [comment]
Ok works now. Looks like the `theme`, `alerts` and `app_image` variables were causing the issue. I replaced them with the ones in the comment you sent.
