### ISSUE TITLE
Default font colour unreadable against dark background 

### ISSUE THREAD

**Issue by fluoridepsychosis** [vednoc/dark-whatsapp#173]
- **Browser**: firefox 78.0.1 (64-bit) 
- **WhatsApp Web version**: Version 2.2027.10
- **Dark-WhatsApp version**: 2.13.0
- **Additional context**: Base foreground colour is set to grey/white but still appears as black
- **Screenshot**: 
![Screenshot from 2020-07-12 22-22-04](https://user-images.githubusercontent.com/48800793/87257011-49751a00-c48f-11ea-84d6-86658903fc05.png)

Apologies if this is a configuration error but it makes no sense to me, even with reset settings I have this error, I have tried editing the foreground colour setting but it appears to do nothing.

**Comment by vednoc** [comment]
You're using an older version of Dark-WhatsApp. Update to `v2.16.1` and everything will be back to normal.
