### ISSUE TITLE
Bug: @ tag font and background are the same colour

### ISSUE THREAD

**Issue by kyle-ds** [vednoc/dark-whatsapp#174]
![image](https://user-images.githubusercontent.com/51097593/88448653-e8393900-cdf4-11ea-8abd-7178d3834683.png)

I'm on 2.16.2 because I use dcferreira's repo, but this has been like this for a couple patches now.

Steps to repo:
1. go to any chat
2. tag using @ symbol. as you start typing the characters turn the same colour as the background

**Comment by vednoc** [comment]
Nice find! It'll be fixed in the next update. Here's a quick preview:

![image](https://user-images.githubusercontent.com/18245694/88449105-90c2b980-ce44-11ea-9134-0a0683f5c027.png)
