### ISSUE TITLE
Option to Disable Expansion of the Side Panel.

### ISSUE THREAD

**Issue by Just-Hussain** [vednoc/dark-whatsapp#177]
**Describe the change you'd like**:
I would like to have an option to disable the expansion of the side panel on hover when minimized.
**Additional context**:
I sometimes find it annoying when it expands while i want to quickly switch a chat and i wait a moment for it to minimize again.
I actually like the little delay in opening and closing it, but i would like an option for it too.
Thx!

**Comment by vednoc** [comment]
You can tweak [hover-on delay][1] duration (I personally use `2.5s`) and that should do the trick. Same applies to [hover-off delay][2] option. 

[1]: https://github.com/vednoc/dark-whatsapp/wiki/Configuration#compact-mode-hover-on-delay
[2]: https://github.com/vednoc/dark-whatsapp/wiki/Configuration#compact-mode-hover-off-delay

**Comment by Just-Hussain** [comment]
Did not notice these great customization options! exactly what i need, thx.

**Comment by vednoc** [comment]
Awesome! It's easy to miss them since we have like 50 other options. 😄
