### ISSUE TITLE
Blog link broken

### ISSUE THREAD

**Issue by kyle-ds** [vednoc/dark-whatsapp#179]
![image](https://user-images.githubusercontent.com/51097593/92243937-193a6e00-ee77-11ea-9bcb-395dcf46dcab.png)
I was going to read it =(

**Comment by vednoc** [comment]
Damn it, every single release I must do something silly. That's the second silly thing I did — the first one is forgetting to include the preview screenshot image. XD

I'll have a look why and where things went wrong.

**Comment by vednoc** [comment]
Seems like my local configuration was at fault, as well as my internet connection failing while doing a `git push`. 😦 The blame is on me for not double-checking if everything went well.

Thank you so much for letting me know about this issue! The blog post is _finally_ live at: https://vednoc.me/blog/next-gen-of-dark-whatsapp 😊
