### ISSUE TITLE
Please add an option to change the read check colour

### ISSUE THREAD

**Issue by Foxk1n** [vednoc/dark-whatsapp#181]
I love everything your style has to offer, however i find it really difficult to differentiate between "read" and the gray "not read". With your previous versions I've been able to just edit the style code myself but I've been unable to do it for this version. If you could add an option that would be amazing, id love to make it vibrant like the default colour

**Comment by vednoc** [comment]
Done! In `v3.3.0` you will be able to change it to any color you like. The two new options that are being added work just like overrides for message bubble colors.

Here's a preview:

![image](https://user-images.githubusercontent.com/18245694/97802421-8a15c080-1c43-11eb-876e-d19c43283538.png)

**Comment by Foxk1n** [comment]
> Done! In `v3.3.0` you will be able to change it to any color you like. The two new options that are being added work just like overrides for message bubble colors.
> 
> Here's a preview:
> 
> ![image](https://user-images.githubusercontent.com/18245694/97802421-8a15c080-1c43-11eb-876e-d19c43283538.png)

Thank you so much! When can I install this update?
