### ISSUE TITLE
Option to hide avatars

### ISSUE THREAD

**Issue by ccatino** [vednoc/dark-whatsapp#183]
Hi, I think it would be nice to have an option to hide avatars from chats. 

I tried WhatsApp Web Skeleton but it hides everything including conversations and emojis.

**Comment by vednoc** [comment]
> I tried WhatsApp Web Skeleton but it hides everything including conversations and emojis.

Yeah, Skeleton is mainly used when taking screenshots for readme and #178.

Just to be sure, you would like the desired effect to be like in the attached image?

![image](https://user-images.githubusercontent.com/18245694/101796690-7ba3aa00-3b09-11eb-9e4e-115fec492f54.png)

**Comment by ccatino** [comment]
Yes, that would be very nice, thank you!
