### ISSUE TITLE
How to customise the day tags in chat?

### ISSUE THREAD

**Issue by Cyberdroid1** [vednoc/dark-whatsapp#184]
### Additional context

![Screenshot 2020-12-19 at 22 48 17](https://user-images.githubusercontent.com/51435948/102695349-b49bf700-424c-11eb-8f51-57dca171912c.png)

How to customise the Yesterday and Today tag?

**Comment by vednoc** [comment]
How would you like to customize them? There are no options to do that at the moment.

**Comment by Cyberdroid1** [comment]
I would like to change their color to follow the accent color. Is it possible?

**Comment by vednoc** [comment]
Yeah! I'll add it in the next release.

**Comment by Cyberdroid1** [comment]
Ok! Thanks!

**Comment by Cyberdroid1** [comment]
Any updates?

**Comment by vednoc** [comment]
Hey @Cyberdroid1, I apologize for late response.

I stopped using WA by the end of December, but I'll try to implement and release a new version by the end of this week. Perhaps @E-RELevant could help out, but I know that his free time is very limited these days.

**Comment by E-RELevant** [comment]
Unfortunately, I really do not have much free time to spare.

Just a quick preview of how I think you could implement this idea:
1. Create a variable of custom system messages color
```css
@var color    sys_msg_bg  'System Messages background color' #364462
```
2. Apply this variable into the `--system-message-background` variables (both regular and rgb)
3. Consider to add some customization under [these lines](https://github.com/vednoc/dark-whatsapp/blob/master/wa.user.styl#L1569-L1579) (refers to the `.KpuSa` class).

**Comment by E-RELevant** [comment]
@vednoc Unfortunately, I really do not have much free time to spare.

Just a quick preview of how I think you could implement this idea:
1. Create a variable of custom system messages color
```css
@var color    sys_msg_bg  'System Messages background color' #364462
```
2. Apply this variable into the `--system-message-background` variables (both regular and rgb)
3. Consider to add some customization under [these lines](https://github.com/vednoc/dark-whatsapp/blob/master/wa.user.styl#L1569-L1579) (refers to the `.KpuSa` class).

**Comment by AvinashReddy3108** [comment]
![Screenshot_20210224_102801](https://user-images.githubusercontent.com/27774996/108949763-e8d0d100-765c-11eb-8e95-4017c859b982.png)

Until then, the `Base blue Color` can be changed like in the screenshot.

**Comment by Cyberdroid1** [comment]
Thanks for fixing this!

**Comment by vednoc** [comment]
I hope it was worth the wait! 😄
