### ISSUE TITLE
starting message is unselectable

### ISSUE THREAD

**Issue by RiedleroD** [vednoc/dark-whatsapp#185]
Not only is the link in the landing page unclickable (which you explained why, no issue here), but it's also unselectable. I'm not sure what causes this problem or how to fix it, since neither is `user-select:none` specified nor does spefifying `user-select:all` or `user-select:text` help. I do hope you'll look into the issue though. Maybe it's something with the way firefox handles pseudo-elements, idk.

- **Browser**: Firefox 84.0.1
- **WhatsApp Web version**: 2.2049.10
- **Dark-WhatsApp version**: Lite 3.5.0

**Comment by vednoc** [comment]
Unfortunately, this is also not possible at the moment. I found out about that a couple of years ago from this [StackOverflow][1] question. There is also a [CSSWG draft][2] for it, so it will be interesting to see where things go.

P.S. If you'd like to [configure various features][3] of Dark-WhatsApp, install the non-Lite version from GitHub. Lite version is mainly used for USo and non-Stylus extensions.


[1]: https://stackoverflow.com/questions/27392228/select-text-in-before-or-after-pseudo-element
[2]: https://github.com/w3c/csswg-drafts/issues/2894
[3]: https://github.com/vednoc/dark-whatsapp/wiki/Configuration

**Comment by RiedleroD** [comment]
I see. Are there plans for an accompanying userscript that would fix problems like these?

**Comment by vednoc** [comment]
Hey @RiedleroD, I apologize for late response.

I don't think a userscript would be necessary, but even so, I doubt it would be used by many. The text changes rarely, but I saw that Dark-Telegram uses a QR code in the intro panel. That's actually a genius idea and something that was so obvious and very easy to implement.
