### ISSUE TITLE
notification number in profile pic?

### ISSUE THREAD

**Issue by Cris721** [vednoc/dark-whatsapp#186]
hey, first of all AWESOME work. it's unbelievable, really.
straight to the point: in compact view, the only way i use whatsapp web, it does not show the notification number unless i hover on the contact and expand to see the notification number.
would it be possible to have it on the profile pic of the contanct? if so, that would be perfect! i'll add a screenshot with what i mean.
![whatsapp web](https://user-images.githubusercontent.com/66562914/109347980-396e4700-7874-11eb-96f5-f33d82397092.png)

**Comment by vednoc** [comment]
It [used to be like that][1], but it seems like the latest update broke it. Search bar is also fully expanded, so that's broken as well.

> hey, first of all AWESOME work. it's unbelievable, really.

I'm glad you like it. Also, thanks for the coffee! 😊 

[1]: https://github.com/vednoc/dark-whatsapp/blob/master/changelog.org#added-13

**Comment by Cris721** [comment]
yes! i thought i remembered something like that, but i wasn't sure. well, let's hope for future updates.

coffee MORE than deserved. you're welcome and thanx again.

**Comment by vednoc** [comment]
I might be able to fix it over the weekend, but I have other things to do. Compact mode is a hack that needs to be done right, and I tend to forget how it comes together thanks to randomly generated selectors. 🤦🏻‍♂️ That will be significantly easier in the future releases since I'm planing to do it in a smart way this time.

**Comment by vednoc** [comment]
Progress report: figured it out for the most part, but "typing..." is still missing its selector. I might release an update tomorrow after that is fixed.
