### ISSUE TITLE
Scrolling is laggy on Firefox

### ISSUE THREAD

**Issue by ghost** [vednoc/dark-whatsapp#193]
- **Browser**: Firefox
- **WhatsApp Web version**: BETA
- **Dark-WhatsApp version**: 3.5.0

Scrolling (and other animations/transitions) is slow and laggy, if style is disabled then scrolling is normal

**Comment by kyle-ds** [comment]
Does this still happen on 3.7?

**Comment by vednoc** [comment]
I'm unable to reproduce this issue. If you're _still_ using DWA v3.5.0, please upgrade to the latest v3.7.0 and try again.

**Comment by E-RELevant** [comment]
Closed due to lack of response. In case it still occurs, please reopen the issue again.
