### ISSUE TITLE
Add option to remove 'Update Available' popup?

### ISSUE THREAD

**Issue by wefalltomorrow** [vednoc/dark-whatsapp#194]
Would be great if there was a way to remove this with the theme:

![image](https://user-images.githubusercontent.com/45746576/144738762-0e140449-2c00-422a-ac24-734acfa01d98.png)

**Comment by vednoc** [comment]
I no longer use WA, so this is not something that I can implement. Moreover, catching a unique selector for that state is _very_ hard; I managed to do it a couple of times during all these years of maintaining DWA. It's a randomly generated one, too, so it would likely break quite often.

**Comment by kyle-ds** [comment]
Finally grabbed the class for that span (through beta in Ferdi anyways): ```document.getElementsByClassName("_3z9_h")[0].style.display="none"``` works. If I have time i'll try and figure out how to put it in the style.

**Comment by wefalltomorrow** [comment]
> Finally grabbed the class for that span (through beta in Ferdi anyways): `document.getElementsByClassName("_3z9_h")[0].style.display="none"` works. If I have time i'll try and figure out how to put it in the style.

Awesome, thank you!

**Comment by vednoc** [comment]
There's an update and a solution to this issue in #199. With the availability of [:has()](https://caniuse.com/css-has) pseudo-class, the fix is pretty trivial.
