### ISSUE TITLE
dark-messenger

### ISSUE THREAD

**Issue by o-r-i-z-u-r-u** [vednoc/dark-whatsapp#195]
Hi vednox I use [messenger](https://www.messenger.com/) (or m.me) instead of facebook's internal pop out for sending messages (only because my fb feed is a dumster fire).

Is there any possibility of adding a dark-style for messenger in future? 

Really appreciate your work on dark-instagram and dark-whatsapp, thank you so much
P.S. your avatar is an obscure reference! 

> Strange events begin to occur as a withdrawn girl named Lain becomes obsessed with interconnected virtual realm of "The Wired".

**Comment by E-RELevant** [comment]
I believe this is a [built-in feature](https://www.facebook.com/help/messenger-app/2137290196561574) of this chat.

**Comment by vednoc** [comment]
> Is there any possibility of adding a dark-style for messenger in future?

Sorry about this really late reply. I don't use that messenger, so this isn't something that I'm able to work on.

> Really appreciate your work on dark-instagram and dark-whatsapp, thank you so much

I'm glad it brought value to you. Major props to @E-RELevant for contributing and the behind-the-scenes work. 🎉 

> P.S. your avatar is an obscure reference!

It's good to know that at least one person figured out the reference! 😊
