### ISSUE TITLE
Compact mode broken

### ISSUE THREAD

**Issue by allanf181** [vednoc/dark-whatsapp#200]
- **Browser**: Opera GX 96.0.4693.104
- **WhatsApp Web version**: 2.2313.8
- **Dark-WhatsApp version**:  3.7.1
- **Additional context**: Broken after last whatsapp web update
- **Screenshot**:
![image](https://user-images.githubusercontent.com/14101716/227669968-fae8c02b-ed72-4124-a1e1-f1856c63d17b.png)

**Comment by vednoc** [comment]
It will be fixed in the next release.
