### ISSUE TITLE
Quotes showing the quoted user's self name/alias in black

### ISSUE THREAD

**Issue by ktopaz** [vednoc/dark-whatsapp#23]
Similar to the issue described in https://github.com/vednoc/onyx/issues/19
But only relevant for when someone is quoted - only then the name is shown in black.
(Names in normal messages outside of quotes are shown correctly)
screenshot to show the issue:
https://imgur.com/GVq5TOa

WhatsApp Web 0.3.2276
WhatsApp by Mew v1.3.0

**Comment by vednoc** [comment]
It seems to only be the case with contacts that aren't in your contact list. Would be great if you could inspect element and grab the CSS snippet that defines its color otherwise I'll have to wait for this to happen on my end in order to fix it. :smiley:

**Comment by ktopaz** [comment]
If I did it correctly (ctrl+shift+I in chrome then inspect element)
it should be:
_3Ye_R _1wjpf

Tested on few various names in few various quotes and this is always the class of the element.
Hope it helps!

**Comment by ktopaz** [comment]
https://imgur.com/a/O59qe8J

**Comment by geisterfurz007** [comment]
Correct. Removing the last class [here](https://github.com/vednoc/onyx/commit/b6231444f3f22fe8a4fbccc269e0049903e4388e) should in theory correct the setting. However there is another rule that prevents this:

```css
html[dir="ltr"] ._3Ye_R {
    color: rgba(0, 0, 0, 0.4) !important;
    margin-left: 8px;
}
```

I have no clue about css and naively tried to include the same rule in the css without the `!important` but that did exactly nothing.

**Comment by Pescovisck** [comment]
```
html[dir="ltr"] ._3Ye_R {
    color: rgba(255, 255, 255, 0.4) !important;
    margin-left: 8px;
}
```

this worked for me
