### ISSUE TITLE
Chat wallpaper + suggestion similar to issue #25

### ISSUE THREAD

**Issue by KDASthenerd** [vednoc/dark-whatsapp#27]
Hi. I have a few suggestions and issues to appoint. You wrote that "any sort of contribution is more than welcome", and I'll be very happy if any of my suggestions get to help you in some way.

First of all, I'm mindblown by the capabilities of CSS customization using browser extensions. I've just found out about it and your project fits perfectly with my likes. I might be a novice in terms of HTML and CSS coding, but I've figured a few things out when researching about the issues and I think I've managed to change the code to make things work. I'll include code sections on each suggestion. I also tried to follow your style of comments and structure (I don't even know if it's a common standard). As to where to add the code, I leave it up to you. Without further ado, here are the suggestions:

1. Chat wallpaper.
  I've noticed that you included a TODO comment on this section of your code. After a lot of searching, I found that the `YUoyu` class has the WhatsApp default "Doodle background", as you call it. As I've always wanted to have chat wallpaper on Web just as it is on mobile, I tried to make it work on this code. (Web allows us to put solid colors as wallpapers, but who wants that?)
  I first created a variable for the wallpaper image, as you did with the background variable `--image`. The variable i created, `--chatwallpaper`, is set as the background image of the class `_1GX8_`. The background size is set to `cover`, so that it fits the chat div.
  The default doodle wallpaper still appears over the `--chatwallpaper` image. To avoid this, I simply set the opacity to 0 on the `YUoyu` class.
  The code inside `:root` to add the variable:
`    --chatwallpaper: url(/* image url here */)`

  The code for this:
```
  /* Chat wallpaper. */
  ._1GX8_ {
    /* Set chat wallpaper image. */
    background-image: var(--chatwallpaper) !important;
    /* Set background image to fit to chat area. */
    background-size: cover !important;
  }
  .YUoyu {
    /* Set default WhatsApp chat background's opacity to 0. */
    opacity: 0 !important;
  }
```

2. Embedded videos missing background color.
  There's an issue that was opened 12 days ago with the exact same title (Issue #25). I gotta say I've arrived in time, and I understand that you might not have answered because not so much time has passed since then. In Issue #25, the person who opened the Issue suggested to add the following code to solve it:
`    ._3C3Sj { background-color: var(--light); }`
  It works fine, but, following the "dark" name of the theme, I think it's fitting to set the background color to `--dark` and setting the text color to `--light` later, which is the exact same thing you did on the sections `/* Document embeds. */` and `/* Link embeds. */`. By the way, the code that I'll suggest can be put inside `/* Link embeds. */`, but, again, I leave it for you to decide where to put my code. I've worked out the code needed for YouTube and Instagram embedded video links, so I'm not sure it will work with other sites, although it looks like it's a standard since both sites share a few style names on the original style code.
  The code for this:
```
  /* Video link embeds. */
  ._3C3Sj {
    /* Embedded video link background color */
    background-color: var(--dark) !important;
  }
  ._2a30d {
    /* Instagram video description OR YouTube video title */
    color: var(--light) !important;
  }
  .vFSKE{
    /* YouTube video description. */
    color: var(--light) !important;
  }
  ._37Q6_{
    /* Domain URL. */
    color: var(--light) !important;
  }
```

P.S.: I've decided to make my own background image on Photoshop, and thought that anyone reading might enjoy it. Here's the link: https://i.imgur.com/WLzE96a.png
There are lines on the top and bottom of the image. I've drawn them to work perfectly on a maximized Google Chrome window with the favorites bar hidden. Put the imgur link in place of the --image variable in order to use it.

**Comment by vednoc** [comment]
Hi! Thank you for making this very detailed post with some great suggestions.


>I'm mindblown by the capabilities of CSS customization using browser extensions. I've just found out about it and your project fits perfectly with my likes.

Awesome! You might also like my other projects that are hosted on [GitLab](https://gitlab.com/users/vednoc/projects) specifically themes for Discord, HackerNews and GitLab itself. The one for Discord has by far the largest amount of custom CSS and the one for GitLab is my largest project up to date.


>I also tried to follow your style of comments and structure (I don't even know if it's a common standard).

Comments are there so we know what obfuscated CSS does. The coding style is *very* weird but it made sense back when I did a major refactor. I've been thinking about refactoring it with [Stylus-lang](http://stylus-lang.com/) but I'm not motivated enough to do it since everything *just works* and it's a nightmare to post updates on userstyles.


>Without further ado, here are the suggestions.

They're looking great! If you'd like to, feel free to open separate pull requests and I'll be happy to merge them. Actually, I encourage **you** to do it! :smile: 


>Put the imgur link in place of the --image variable in order to use it.

Since I exposed that variable in the configuration menu, simply click on Stylus icon on your toolbar then on the configure (gear icon) button and replace the existing link with a new one.

Editing code locally prevents auto-update and that's not an ideal situation because the only way to get auto-update back is to force update the theme and that'll remove all local changes. If you want to add/change/test styles, a better way is to make a companion style -- just a separate style that applies to the same website.

<br>
If you have any questions, do let me know. :smiley:

**Comment by tinyCoder32** [comment]
Hi, i hope you don't mind sharing the [extension link](https://chrome.google.com/webstore/detail/wa-web-plus/ekcgkejcjdcmonfpmnljobemcbpnkamh) here too, which uses your CSS project as a major function, it has the option to easily change the background image of the chats also, with a customization panel for the night mode colors.

**Comment by KDASthenerd** [comment]
Hi. Thanks a lot for sending me this email. I had to rework the CSS code when the WhatsApp Web site went through an update XD. All the classes had other names, and it was a mess. This extension makes it a lot easier, mostly of course for users that don’t want to get messy with code, which includes me. It looks great, and I’m very happy with the results.

I’m just worried about the default chat background still being visible, albeit just a little bit (https://web.whatsapp.com/img/bg-chat-tile_8a055527b27b887521a9f084497d8879.png).
I’m currently using a temporary Stylus code to work around the issue, and I really think that it’d be nice if you implemented this function to your extension, which is already great.
The background is located on a div with class=”fzCXy”, and the image is in the aforementioned link. It can be disabled simply with this code I’m currently using:

.fzCXy {
  background-image: none !important;
}


Two more things, both related to the custom background image URL text box in the extension menu.
Is it possible to save the link in case the user switches the “custom background image” off and on again? I think it would be best if the text box “remembers” what was the last image it used.
Last thing, when pasting the link, a “Save” button appears. Is it possible to trigger the save option with the Enter key? It’s because I’m a “keyboard user”, I’d say, he he. I believe other users like me would like to set an image as background without the need to grab the mouse.

All things considered, it’s a very good extension, and I’m happy that I found it. I’m looking forward to its future development. Congratulations and keep up the good work!

De: tinyCoder32
Enviado:Monday, June 3, 2019 8:15 PM
Para: vednoc/onyx
Cc:KDASthenerd; Author
Assunto: Re: [vednoc/onyx] Chat wallpaper + suggestion similar to issue #25(#27)

Hi, i hope you don't mind sharing the extension link here too, which uses your CSS project as a major function, it has the option to easily change the background image of the chats also, with a customization panel for the night mode colors.

**Comment by tinyCoder32** [comment]
Thank you so much for the suggestions and i'm happy you found it useful. I guess you are right, I must keep the last used background image saved when the option is switched off.

I will take your notes into my considerations for the next version in a few days god willing.

**Comment by tinyCoder32** [comment]
> Two more things, both related to the custom background image URL text box in the extension menu. Is it possible to save the link in case the user switches the “custom background image” off and on again? I think it would be best if the text box “remembers” what was the last image it used. Last thing, when pasting the link, a “Save” button appears. Is it possible to trigger the save option with the Enter key? It’s because I’m a “keyboard user”, I’d say, he he. I believe other users like me would like to set an image as background without the need to grab the mouse.

You can update in 60 minutes to Version 2.0.4, the first suggestion was great, now the plugin remembers the last background url you saved. Enter key saving will be in the next update god willing.
