### ISSUE TITLE
Question: Change default color-scheme?

### ISSUE THREAD

**Issue by vednoc** [vednoc/dark-whatsapp#32]
Pretty much what the title says.

Personally, I didn't use the default color-scheme for a very long time. The only reason I kept it for so long is because it is more recognizable than other themes on USo. I haven't seen too many people change the colors, so I'm not sure what to do.

This is what it could look like. Colors go in line with my other themes, but I'm open to changing them.
![image](https://user-images.githubusercontent.com/18245694/58836346-d9278280-8658-11e9-9555-f5fe7fdf3491.png)

Vote here! 
[![](https://api.gh-polls.com/poll/01DCFMF76X6YNVC0TKNJYHS99R/Keep%20the%20old%20one)](https://api.gh-polls.com/poll/01DCFMF76X6YNVC0TKNJYHS99R/Keep%20the%20old%20one/vote)
[![](https://api.gh-polls.com/poll/01DCFMF76X6YNVC0TKNJYHS99R/Change%20it!)](https://api.gh-polls.com/poll/01DCFMF76X6YNVC0TKNJYHS99R/Change%20it!/vote)

**Comment by tinyCoder32** [comment]
Hello again @vednoc , as promised before, people can customize your nice work with a nice chrome extension, would you mind testing it please?
https://chrome.google.com/webstore/detail/wa-web-plus/ekcgkejcjdcmonfpmnljobemcbpnkamh

**Comment by vednoc** [comment]
Hey @tinyCoder32, please keep to the scope of this and other issues.

I appreciate your work but I cannot test your extension for two reasons:
1. I don't use proprietary extensions.
2. I keep the extension list down to the minimum.

**Comment by tinyCoder32** [comment]
> Hey @tinyCoder32, please keep to the scope of this and other issues.
> 
> I appreciate your work but I cannot test your extension for two reasons:
> 
> 1. I don't use proprietary extensions.
> 2. I keep the extension list down to the minimum.

Hi @vednoc 
I totally understand, i'm sorry.

Thanks for your efforts.

**Comment by richardcane** [comment]
I think it'd be a great idea to do this as some sort of theming switch if that's possible. I really like the original scheme with the blue, I think it's a little less harsh than black and orange.

**Comment by Pescovisck** [comment]
Since the day i installed this theme, i changed the vars to this black and orange theme (my favorite colors).
As the meme say: 

> I see this as an absolute win

**Comment by vednoc** [comment]
> @richardcane: I think it'd be a great idea to do this as some sort of theming switch if that's possible.

It is, but it's a bit complicated to set up properly and I'd have to do it for every single theme I have. That is exactly why I made the [theme switcher](https://gitlab.com/vednoc/theme_switcher) and it works great, though it does need more color-schemes. :smiley:

**Comment by richardcane** [comment]
I mean if we're talking userstyles wouldn't it be as simple as having a theme dropdown with different preset`:root` element values?

**Comment by vednoc** [comment]
> I mean if we're talking userstyles wouldn't it be as simple as having a theme dropdown with different preset :root values?

It would be possible to have multiple :root presets, the problem is having too many of them -- the reason why theme switcher exists. Another problem that rises is, for the upcoming rewrite in [stylus-lang](http://stylus-lang.com), I don't know of a good way to accomplish that.

> Assuming that dropdown had no given theme selected, defer to theme switcher or default theme (black and orange).

Default theme would be the case. Theme switcher will always override colors IF it's installed after the WhatsApp theme -- if necessary, that could be prevented in many different ways.

> Having had a quick look at the theme switcher it looks like each individual option can be modified, but there are no full-suite named themes to choose from? Purely from a UX perspective, for users that just want something that "looks functional", that can be a bit overwhelming.

I agree, the UX sucks, but I don't expect majority of people to be changing colors all the time -- for me it's more of a _set it and forget it_ type of thing. Not sure whether I should group the colors since this way people can mix and match colors from various color-schemes.

> I think it's a good idea to align the defaults with your other projects.

It's gonna be alright. I really appreciate the input from the community and I'm fine with whatever is chosen. At the end of the day the theme switcher is doing an awesome job for me personally, and it's super easy to adjust colors for those that want to do it. :smile:

**Comment by vednoc** [comment]
The dropdown menu with color presets is implemented in v2, and the old color-scheme will be kept as default because it had 60% of votes (or more at one point). Thanks to everyone that participated!

Closing this.
