### ISSUE TITLE
Add possibility to change Text alignment 

### ISSUE THREAD

**Issue by Soyde** [vednoc/dark-whatsapp#58]
It would be great if you could add an option to change bubble text alignment.

For example, I don't like the right alignment for messages sent.
In my case I have changed the following html 

.message-out {
    justify-content: flex-start;
}

It would be great if you could add this to the predefined options and give the user to change message-in or message-out alignment according to their preferences.

Thanks for your great effort!
Best regards.

**Comment by vednoc** [comment]
Not sure how useful it would be right now considering both bubbles have the same color. However, I did implement it in v2, and it looks quite good with different colors!

Thanks for the suggestion and kind words. :smiley:

**Comment by Soyde** [comment]
How can I test v2? 
I usually use Stylus with https://raw.githubusercontent.com/vednoc/onyx/master/WhatsApp.user.css

**Comment by vednoc** [comment]
Hey @Soyde, apologies for not seeing this earlier.

I just updated #38 with the work done so far. It's by no means perfect, but it's getting there. You can install it using [this link](https://github.com/vednoc/onyx/raw/stylus-rewrite/wa.user.styl), I'm just not sure whether if it will auto-update when I push new changes.
