### ISSUE TITLE
Visual bugs

### ISSUE THREAD

**Issue by E-RELevant** [vednoc/dark-whatsapp#59]
Message settings (arrow) using data:
![image](https://user-images.githubusercontent.com/20738487/68465636-7c3d8300-021b-11ea-9785-3f7a422112aa.png)

Voice Message Timeline color:
![image](https://user-images.githubusercontent.com/20738487/68465839-e48c6480-021b-11ea-9a33-2028c6c981c7.png)

Loading while scrolling up color:
![image](https://user-images.githubusercontent.com/20738487/68465927-130a3f80-021c-11ea-9035-909aa01eae59.png)

Search messages loading color (+too close to the corner):
![image](https://user-images.githubusercontent.com/20738487/68466029-477dfb80-021c-11ea-86f8-fd13c3b3897f.png)

Login screen - Keep me signed in no color change:
![image](https://user-images.githubusercontent.com/20738487/68466380-f6223c00-021c-11ea-83b4-ab5f38d28568.png)

Contact - no divider:
![image](https://user-images.githubusercontent.com/20738487/68467464-e73c8900-021e-11ea-9be9-bef45dfe866c.png)![image](https://user-images.githubusercontent.com/20738487/68467478-ec99d380-021e-11ea-8903-f421110cf0bc.png)

Quotes should be more noticeable, same as links:
• a message with a link -
![image](https://user-images.githubusercontent.com/20738487/68465636-7c3d8300-021b-11ea-9785-3f7a422112aa.png)
• a quoted message on original version -
![image](https://user-images.githubusercontent.com/20738487/68476157-ae0e1400-0232-11ea-9123-5c1c52242943.png)
• a quoted message using 'onyx' -
![image](https://user-images.githubusercontent.com/20738487/68476237-d8f86800-0232-11ea-8b34-7784555081c2.png)

Emoji's background:
![image](https://user-images.githubusercontent.com/20738487/68469093-202a2d00-0222-11ea-9d9e-bb479be01fee.png)

**Comment by vednoc** [comment]
Everything except emoji's background is fairly simple to fix.

Emojis would require removing the background from source images, e.g. [one of the many](https://web.whatsapp.com/img/emoji-61-32_18ebdb7c0581fc3a8fc8ed9f91ad0ece.webp), and then we'll need a place to host them which could be done here, on GitHub.

**Comment by E-RELevant** [comment]
> Everything except emoji's background is fairly simple to fix.
> 
> Emojis would require removing the background from source images, e.g. [one of the many](https://web.whatsapp.com/img/emoji-61-32_18ebdb7c0581fc3a8fc8ed9f91ad0ece.webp), and then we'll need a place to host them which could be done here, on GitHub.

It seems like using 'Chrome DevTools' got me to the source file fairly easily.
![image](https://user-images.githubusercontent.com/20738487/68475738-9b470f80-0231-11ea-8610-8ef075e66be4.png)

**Comment by vednoc** [comment]
Try inspecting emojis in the emoji menu and you'll see what I'm talking about. There are also different sizes of emojis.

**Comment by vednoc** [comment]
Quick update: Got emoji background sorted out thanks to another project. :tada: Will be live in v1 and v2 shortly.

![image](https://user-images.githubusercontent.com/18245694/68491422-1f59c100-024b-11ea-80a6-23405e87d2da.png)

**Comment by E-RELevant** [comment]
> Quick update: Got emoji background sorted out thanks to another project. 🎉 Will be live in v1 and v2 shortly.
> 
> ![image](https://user-images.githubusercontent.com/18245694/68491422-1f59c100-024b-11ea-80a6-23405e87d2da.png)

Lovely! Thanks! The others as well?

**Comment by vednoc** [comment]
> Lovely! Thanks! The others as well?

Probably during the weekend. I'm supposed to study for tomorrow, and I spent quite a while messing around with emojis. :sweat_smile:

**Comment by tinyCoder32** [comment]
> > Lovely! Thanks! The others as well?
> 
> Probably during the weekend. I'm supposed to study for tomorrow, and I spent quite a while messing around with emojis. 😅

Very nice work man, bravo!

**Comment by vednoc** [comment]
> Very nice work man, bravo!

Wouldn't have been possible without @Slyther's tool. Kudos to him! :blush:

**Comment by Slyther** [comment]
> 
> 
> > Very nice work man, bravo!
> 
> Wouldn't have been possible without @Slyther's tool. Kudos to him! 😊

Hey, thanks for the mention! Glad my tool could help! 😁
