### ISSUE TITLE
Update failed: server responded with code 404.

### ISSUE THREAD

**Issue by ktopaz** [vednoc/dark-whatsapp#68]
Trying to update or check for updated via stylus extensions results with message: 
"Update failed: server responded with code 404."
![(Screenshot: 2019-12-09_09-22-27)](https://user-images.githubusercontent.com/5072830/70415674-dd988200-1a65-11ea-9d86-ad45f92f4f14.png)

I uninstalled the theme from stylus and re-installed the latest from the install link specified in the repo's README (https://raw.githubusercontent.com/vednoc/onyx/master/WhatsApp.user.css)
but the issue remains, still 404 when checking for updates.

**Comment by vednoc** [comment]
Will be fixed now that I renamed the repository. My apologies for late reply.
