### ISSUE TITLE
Get rid of the notification begging box

### ISSUE THREAD

**Issue by runxel** [vednoc/dark-whatsapp#88]
**Describe the change you'd like**:
Hey there! 
First things first: I totally love this dark mode of yours, especially great with the theme switcher.

However I'd like to make a valuable addition and get rid of the notification-enable-begging message box. It's totally superfluous (no, I don't want to have any desktop notifications) and takes away so much of the screen estate.
Of course this needs it's own setting.

If you agree I'd make a PR ready :)
(Basically just another switch + display: none; rule)

**Comment by E-RELevant** [comment]
Interesting suggestion.
Might be smart to make a new configuration option of "**Show head notifications**" and include 3 options:
1. Show
2. Hide browser's notification
3. Hide

**Comment by runxel** [comment]
>     2\. Hide browser's notification

Firefox startet to **not** show the notification, _that there are notifications available_ (🤦‍♂) anyway... Or do I miss what you meant?
