### ISSUE TITLE
White color on search bar and main page

### ISSUE THREAD

**Issue by otaviopires** [vednoc/dark-whatsapp#89]
- **Browser**: Windows 10 - Chrome Version 79.0.3945.130 (Official Build) (64-bit)
- **Dark-WhatsApp version**: v1.22.188
- **Additional context**: it just started few minutes before I opened this issue
- **Screenshot**: 
![image](https://user-images.githubusercontent.com/1145551/72559927-b44cec00-3884-11ea-8e65-748b8af3d0d6.png)

**Comment by vednoc** [comment]
Working on it. The fix will be out soon!

**Comment by vednoc** [comment]
The fix is out now for v1, USo, and will be out for v2 in just a few minutes. I _highly_ recommend that everyone install the v2 if they haven't already.

Will be closing this issue in ~24 hours so that someone doesn't open a similar issue.

**Comment by otaviopires** [comment]
It fixed for me, I tried to update via https://userstyles.org/styles/142096/dark-whatsapp-theme-by-mew but I keep getting v1.
How can I garantee to always have v2 installed?

**Comment by vednoc** [comment]
> How can I garantee to always have v2 installed?

You can find more info on [wiki/installation](https://github.com/vednoc/dark-whatsapp/wiki/Installation) page. Long story short, just click on the install badge and confirm that you want to install the userstyle then disable/remove the v1 so they don't cause conflicts. :smiley:

**Comment by otaviopires** [comment]
Thank man! It works fine!
