### ISSUE TITLE
Status colors are the same if they are viewed or not

### ISSUE THREAD

**Issue by pnadalini** [vednoc/dark-whatsapp#91]
I'm currently using v2.0.6 of dark-whatsapp.
When I go to the status page, it shows all the status with the same color, when the already seen ones should have a different color. Here's a picture of the issue:
![image](https://user-images.githubusercontent.com/26207809/72632460-eeb59800-391b-11ea-8917-17b512c523c0.png)

Normally it looks like this:
![image](https://user-images.githubusercontent.com/26207809/72632183-5e775300-391b-11ea-8bc9-810332196688.png)

It can be fixed changing the style of the circle inside the svg, as you can see with the following image there's a class name for unseen status
`._3yudO`
And for seen status there's a class in that exact position 
`._3J6CL`
![image](https://user-images.githubusercontent.com/26207809/72632656-5966d380-391c-11ea-862e-3320b4e6f2c6.png)

**Comment by E-RELevant** [comment]
Two small requests to help resolve the issue:
1. Do you have the option to add the code for this area?
    - A detailed explanation of how to do this can be found [here](https://github.com/vednoc/dark-whatsapp/blob/master/contributing.org#i-dont-know-css)
2. Can you take a screenshot of what it looks like without using the UserCSS?

**Comment by pnadalini** [comment]
> Two small requests to help resolve the issue:
> 
> 1. Do you have the option to add the code for this area?
>    
>    * A detailed explanation of how to do this can be found [here](https://github.com/vednoc/dark-whatsapp/blob/master/contributing.org#i-dont-know-css)
> 2. Can you take a screenshot of what it looks like without using the UserCSS?

I've updated the issue with the changes you requested

**Comment by otaviopires** [comment]
Is this fix mapped to a version yet? Mine still outdated.
