### ISSUE TITLE
Custom width for the left column

### ISSUE THREAD

**Issue by igorsantos07** [vednoc/dark-whatsapp#95]
I like using a small screen for WhatsApp, but not so small as the compact style does - hiding entirely the message previews. I'd like to be able to set a smaller width for that column, leaving more space for the chats but still seeing the beginning of the message previews :)

And congratulations for the great work!

**Comment by vednoc** [comment]
To implement this, we'll first need more information about your use-case.

1. What is the screen size that you are using? 
2. Would you like this to only work outside of the compact mode?
3. In order for us to test, what would be the ideal size of the left pane?

**Comment by vednoc** [comment]
Hey @igorsantos07, just pinging you in case you haven't seen my reply. :smiley:

**Comment by E-RELevant** [comment]
Closes due to inactivity. @igorsantos07 You can reopen it at any time, but we would love to know more details.
